<template><main class="page"><section class="hero"><div class="wrap"><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><div class="crumb"><NuxtLink to="/spec-library">Spec Library</NuxtLink> / <NuxtLink to="/spec-library/engine-lathes">Engine Lathes, Mills & Drills</NuxtLink> / {{ maker?.name }}</div><h1>{{ maker?.name }} Engine Lathe, Mill & Drill Specifications</h1><p>Browse historical {{ maker?.name }} conventional machine records by model and recorded configuration.</p></div></section><section class="wrap section" v-if="maker"><h2>{{ maker.name }} Models</h2><div class="grid"><NuxtLink v-for="m in models" :key="m.slug" :to="'/spec-library/'+maker.slug+'/engine-lathes/'+m.slug" class="card"><strong>{{m.model}}</strong><span>{{m.count}} historical record{{m.count===1?'':'s'}}</span></NuxtLink></div></section><section v-else class="wrap section"><h2>Manufacturer not found</h2><NuxtLink to="/spec-library/engine-lathes">Return to library</NuxtLink></section></main></template>
<script setup>
import { historicalModelSummaries } from '~/utils/historicalSpecLibrary'
const route=useRoute()
const slugify=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const manufacturerName=String(route.params.manufacturer||'').split('-').map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(' ')
const isConventional=m=>{const x=String(m.WebDesc||m.Web_Desc||'').trim().toLowerCase();return x==='lathes, manual'||x==='mills, manual'||x==='mills, cnc'||x==='radial arm drills'||x==='drills, turret'||x==='drills, gun'||x==='jig mills'||x==='jig mills, cnc'||x==='drills, h.d. & sensitive, multi spindle'||x==='drills, heavy duty & sensitive, sgl. vert. spdl.'||x==='drills, structural, multi spdl'||x==='millers, gantry, n/c & cnc'}
const models=historicalModelSummaries({manufacturer:manufacturerName,machineFilter:isConventional})
const maker=computed(()=>models.length?{name:manufacturerName,slug:slugify(manufacturerName)}:null)
if(!maker.value)setResponseStatus(404)
useSeoMeta({title:()=>maker.value?`${maker.value.name} Machine Specifications | UMS Spec Library`:'Machine Specifications | UMS',description:()=>maker.value?`Historical ${maker.value.name} engine lathe, manual mill, drilling and conventional machine specifications.`:'Historical machine specifications.'})
</script><style scoped>.page{color:#17273a}.wrap{max-width:1200px;margin:auto;padding:0 28px}.hero{background:#0b2545;color:#fff;padding:42px 0;border-bottom:4px solid #f47b20}.kicker{font-size:.78rem;font-weight:900;letter-spacing:.12em;color:#f47b20;margin-bottom:10px}.crumb,.crumb a{color:#c9d8e8}.hero h1{font-size:clamp(2rem,4vw,3rem)}.section{padding:40px 28px 80px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.card{display:flex;flex-direction:column;padding:15px;border:1px solid #d7e0e8;border-radius:7px;text-decoration:none;color:#17273a}.card strong{color:#0b2545}.card span{color:#68798a;font-size:.88rem;margin-top:5px}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style>