<template><main v-if="manufacturer&&machine" class="page"><section class="hero"><div class="wrap"><nav><NuxtLink to="/spec-library">Spec Library</NuxtLink> / <NuxtLink to="/spec-library/automatics">Automatics</NuxtLink> / <NuxtLink :to="`/spec-library/automatics/${manufacturerSlug}`">{{manufacturer}}</NuxtLink> / {{machine}}</nav><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>{{manufacturer}} {{machine}} Specifications</h1><p>Historical Automatics specifications from exact UMS machine records.</p></div></section><section class="wrap section"><div class="warning"><strong>Historical reference information — not a machine-for-sale listing.</strong> Specifications can vary by year and configuration.</div><div class="label">WEB_DESC</div><div class="types"><span v-for="type in webDescs" :key="type">{{type}}</span></div><h2>Historical {{machine}} Specifications by Year</h2><p>Each block below represents an individual historical machine. Specification rows are displayed only when their invid exactly matches that machine's InvID.</p><HistoricalSpecConfigurations :configurations="configurations"/><SpecInventoryMatches :manufacturer="manufacturer" :model="machine"/></section></main><main v-else class="missing"><h1>Automatics model not found</h1><NuxtLink to="/spec-library/automatics">Browse Automatics</NuxtLink></main></template>
<script setup>
import historicalMachines from '~/assets/data/historical-machines.json'
import historicalSpecifications from '~/assets/data/historical-specifications.json'
const route=useRoute(),manufacturerSlug=String(route.params.manufacturer||''),modelSlug=String(route.params.model||'')
const clean=s=>String(s||'').trim()
const slugify=s=>clean(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const groupMachines=historicalMachines.filter(m=>clean(m.Groups)==='Automatics')
const manufacturer=[...new Set(groupMachines.map(m=>clean(m.Manufacturer)).filter(Boolean))].find(name=>slugify(name)===manufacturerSlug)||''
const manufacturerMachines=manufacturer?groupMachines.filter(m=>clean(m.Manufacturer)===manufacturer):[]
const machine=[...new Set(manufacturerMachines.map(m=>clean(m.Model)).filter(Boolean))].find(name=>slugify(name)===modelSlug)||''
if(!manufacturer||!machine)setResponseStatus(404)
const specsByInvID=new Map()
for(const row of historicalSpecifications){const id=clean(row.invid);if(!id)continue;if(!specsByInvID.has(id))specsByInvID.set(id,[]);specsByInvID.get(id).push(row)}
const configurations=computed(()=>manufacturer&&machine?manufacturerMachines.filter(m=>clean(m.Model)===machine).map(m=>{const invID=clean(m.InvID);return{invID,machine:m,specs:specsByInvID.get(invID)||[]}}).filter(c=>c.specs.length>0).sort((a,b)=>clean(b.machine.Year).localeCompare(clean(a.machine.Year),undefined,{numeric:true})):[])
const webDescs=manufacturer&&machine?[...new Set(manufacturerMachines.filter(m=>clean(m.Model)===machine).map(m=>clean(m.WebDesc||m.Web_Desc)).filter(Boolean))].sort((a,b)=>a.localeCompare(b)):[]
useSeoMeta({title:()=>manufacturer&&machine?`${manufacturer} ${machine} Specifications | UMS Spec Library`:'Automatics Specifications | UMS',description:()=>manufacturer&&machine?`Historical ${manufacturer} ${machine} automatic machinery specifications by year and configuration from exact UMS records.`:'Historical automatic machinery specifications.'})
useHead(()=>({link:[{rel:'canonical',href:`https://www.usedmachinerysource.com/spec-library/automatics/${manufacturerSlug}/${modelSlug}`}]}))
</script><style scoped>.page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0;border-bottom:4px solid #f47b20}.hero nav,.hero a{color:#c8d9eb}.kicker,.label{color:#f47b20;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;margin-bottom:28px}.types{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:28px}.types span{background:#f5f7fa;border:1px solid #d8e0e8;border-radius:6px;padding:8px 11px;font-weight:700}.section h2{color:#0b2545}.missing{padding:60px}</style>