<template><main class="page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library" class="back">← Spec Library</NuxtLink><div class="kicker">BROWSE HISTORICAL SPECIFICATIONS</div><h1>Manufacturers &amp; Models</h1><p>Browse historical specification pages directly by manufacturer, machine type and model.</p></div></section><section class="wrap section"><div v-for="m in directory" :key="m.name" class="manufacturer"><h2>{{m.name}}</h2><div v-for="t in m.types" :key="t.key" class="type"><h3>{{t.label}}</h3><div class="models"><NuxtLink v-for="item in t.models" :key="item.model+'|'+item.type" :to="modelUrl(m.name,item.model,item.type)">{{item.model}}</NuxtLink></div></div></div></section></main></template>
<script setup>
import historicalMachines from '~/assets/data/historical-machines.json'
import {clean,rawType,displayType,typeKind,modelUrl} from '~/utils/specLibraryBrowse'
const rows=historicalMachines.filter(m=>clean(m.Manufacturer)&&clean(m.Model)&&rawType(m))
const order={lathe:0,vmc:1,hmc:2}
const directory=[...new Set(rows.map(m=>clean(m.Manufacturer)))].sort((a,b)=>a.localeCompare(b)).map(name=>{const mine=rows.filter(r=>clean(r.Manufacturer)===name),map=new Map();for(const r of mine){const raw=rawType(r),kind=typeKind(raw),key=kind==='other'?raw:kind;if(!map.has(key))map.set(key,{key,label:displayType(raw),rows:[]});map.get(key).rows.push(r)}const types=[...map.values()].sort((a,b)=>(order[a.key]??3)-(order[b.key]??3)||a.label.localeCompare(b.label)).map(t=>({...t,models:[...new Map(t.rows.map(r=>[clean(r.Model).toLowerCase(),{model:clean(r.Model),type:rawType(r)}])).values()].sort((a,b)=>a.model.localeCompare(b.model,undefined,{numeric:true}))}));return{name,types}})
useSeoMeta({title:'Machine Manufacturers & Models | UMS Spec Library',description:'Browse historical machinery specification pages directly by manufacturer, machine type and model.'})
</script>
<style scoped>.page{color:#17273a;padding-bottom:60px}.wrap{max-width:1200px;margin:auto;padding:0 28px}.hero{background:#0b2545;color:#fff;padding:46px 0;border-bottom:4px solid #f47b20}.back{color:#c8d9eb}.kicker{color:#f47b20;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:16px 0 8px}.hero h1{font-size:3rem;margin:0}.section{padding-top:34px}.manufacturer{margin-bottom:38px;padding-bottom:24px;border-bottom:1px solid #d7e0e8}.manufacturer h2{color:#0b2545;font-size:1.7rem;margin:0 0 18px}.type{margin:0 0 20px}.type h3{color:#526579;font-size:1rem;margin:0 0 9px}.models{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px}.models a{padding:9px 10px;border:1px solid #d7e0e8;border-radius:6px;color:#1c4587;text-decoration:none;font-weight:700}.models a:hover{border-color:#f47b20}@media(max-width:900px){.models{grid-template-columns:repeat(3,1fr)}}@media(max-width:600px){.models{grid-template-columns:repeat(2,1fr)}.wrap{padding:0 18px}}</style>