<template><main v-if="manufacturer&&machine" class="page"><section class="hero"><div class="wrap"><nav><NuxtLink to="/spec-library">Spec Library</NuxtLink> / <NuxtLink :to="`/spec-library/${slug}`">{{title}}</NuxtLink> / <NuxtLink :to="manufacturerLink">{{manufacturer}}</NuxtLink> / {{machine}}</nav><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>{{manufacturer}} {{machine}} Specifications</h1><p>{{modelMachines.length}} historical machine record{{modelMachines.length===1?'':'s'}}.</p></div></section><section class="wrap section"><div class="warning"><strong>Historical reference information — not a machine-for-sale listing.</strong> Specifications can vary by year and configuration.</div><div class="label">MACHINE TYPE</div><div class="types"><span v-for="type in webDescs" :key="type">{{type}}</span></div><h2>Historical {{machine}} Specifications by Year</h2><p>Each block represents one machine record. Specifications are joined only by exact InvID. When detailed specifications were not recorded for an InvID, the machine record is still shown.</p><HistoricalSpecConfigurations :configurations="configurations"/><SpecInventoryMatches :manufacturer="manufacturer" :model="machine"/></section></main><main v-else class="missing"><h1>{{title}} model not found</h1><NuxtLink :to="`/spec-library/${slug}`">Browse {{title}}</NuxtLink></main></template>
<script setup>
import historicalMachines from '~/assets/data/historical-machines.json';import historicalSpecifications from '~/assets/data/historical-specifications.json'
const props=defineProps({group:{type:String,required:true},title:{type:String,required:true},slug:{type:String,required:true}}),route=useRoute(),manufacturerSlug=String(route.params.manufacturer||''),modelSlug=String(route.params.model||''),clean=s=>String(s||'').trim(),slugify=s=>clean(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),machineType=m=>clean(m.WebDesc||m.Web_Desc)
// Historical JSON presence is the library inclusion rule. sold, off_market and dont_advertise are intentionally ignored.
const groupMachines=historicalMachines.filter(m=>clean(m.Groups)===props.group),manufacturer=[...new Set(groupMachines.map(m=>clean(m.Manufacturer)).filter(Boolean))].find(name=>slugify(name)===manufacturerSlug)||'',allManufacturerMachines=manufacturer?groupMachines.filter(m=>clean(m.Manufacturer)===manufacturer):[],availableTypes=[...new Set(allManufacturerMachines.map(machineType).filter(Boolean))],requestedType=clean(route.query.type),activeType=availableTypes.includes(requestedType)?requestedType:'',manufacturerMachines=activeType?allManufacturerMachines.filter(m=>machineType(m)===activeType):allManufacturerMachines,machine=[...new Set(manufacturerMachines.map(m=>clean(m.Model)).filter(Boolean))].find(name=>slugify(name)===modelSlug)||'';if(!manufacturer||!machine)setResponseStatus(404)
const modelMachines=manufacturer&&machine?manufacturerMachines.filter(m=>clean(m.Model)===machine):[],specsByInvID=new Map();for(const row of historicalSpecifications){const id=clean(row.invid);if(!id)continue;if(!specsByInvID.has(id))specsByInvID.set(id,[]);specsByInvID.get(id).push(row)}
const configurations=computed(()=>modelMachines.map(m=>{const invID=clean(m.InvID);return{invID,machine:m,specs:specsByInvID.get(invID)||[]}}).sort((a,b)=>clean(b.machine.Year).localeCompare(clean(a.machine.Year),undefined,{numeric:true}))),webDescs=[...new Set(modelMachines.map(machineType).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),manufacturerLink=computed(()=>({path:`/spec-library/${props.slug}/${manufacturerSlug}`,query:activeType?{type:activeType}:{}}))
useSeoMeta({title:()=>manufacturer&&machine?`${manufacturer} ${machine} Specifications | UMS Spec Library`:`${props.title} Specifications | UMS`,description:()=>manufacturer&&machine?`Historical ${manufacturer} ${machine} specifications by year from exact UMS records.`:`Historical ${props.title.toLowerCase()} specifications.`});useHead(()=>({link:[{rel:'canonical',href:`https://www.usedmachinerysource.com/spec-library/${props.slug}/${manufacturerSlug}/${modelSlug}`}]}))
</script><style scoped>.page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0;border-bottom:4px solid #f47b20}.hero nav,.hero a{color:#c8d9eb}.kicker,.label{color:#f47b20;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;margin-bottom:28px}.types{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:28px}.types span{background:#f5f7fa;border:1px solid #d8e0e8;border-radius:6px;padding:8px 11px;font-weight:700}.section h2{color:#0b2545}.missing{padding:60px}</style>