<template><main class="library"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/cnc-lathes" class="back">← CNC Lathe Specification Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>{{ manufacturer }} CNC Lathe Specifications</h1><p>Browse historical {{ manufacturer }} CNC lathe and turning-center specifications by exact model designation, year and recorded configuration.</p></div></section><section class="wrap body"><section v-if="currentMachines.length" class="current"><div class="eyebrow">FOR SALE NOW</div><h2>Current {{ manufacturer }} CNC Lathes</h2><div class="current-grid"><NuxtLink v-for="m in currentMachines" :key="m.InvID" :to="`/equipment/${m.InvID}/${machineSlug(m)}`" class="current-card"><strong>{{ m.Year }} {{ m.Manufacturer }} {{ m.Model }}</strong><span>{{ m.WebDesc }}</span><small>Stock #{{ m.InvID }}</small></NuxtLink></div></section><section class="browse"><div class="eyebrow">SPECIFICATION LIBRARY</div><h2>Browse {{ manufacturer }} Models</h2><p class="intro">Model names are preserved exactly as recorded in UMS historical records. Similar-looking model designations are not automatically combined.</p><input v-model="query" class="search" type="search" :placeholder="`Search ${manufacturer} models`"><div class="model-grid"><NuxtLink v-for="entry in filteredEntries" :key="entry.slug" :to="`/spec-library/${routeSlug}/${entry.slug}`" class="model-card"><strong>{{ entry.model }}</strong><span>{{ entry.records.length }} historical {{ entry.records.length===1?'record':'records' }}</span><small>{{ yearRange(entry) }}</small></NuxtLink></div><p v-if="!filteredEntries.length" class="empty">No models match that search.</p></section><div class="warning"><strong>Historical specification information — not machines currently for sale.</strong> Specifications reflect individual machines previously recorded by UMS and can vary by year, control, configuration and options.</div><section class="cta"><h2>Need a {{ manufacturer }} CNC lathe?</h2><p>Tell us what model or machine type you need and Used Machinery Source can help locate it.</p><NuxtLink to="/equipment#tell-us-what-you-need">Tell Us What You Need</NuxtLink></section></section></main></template>
<script setup>
import { computed, ref } from 'vue'
import machinesData from '~/assets/data/machines.json'
const props=defineProps({manufacturer:{type:String,required:true},routeSlug:{type:String,required:true},entries:{type:Array,required:true},aliases:{type:Array,default:()=>[]}})
const query=ref('')
const filteredEntries=computed(()=>{const q=query.value.trim().toLowerCase();return props.entries.filter(e=>e.records?.some(r=>r.specs?.length||r.recordedSpecs?.trim())).filter(e=>!q||e.model.toLowerCase().includes(q))})
const names=computed(()=>[props.manufacturer,...props.aliases].map(x=>x.toLowerCase()))
const currentMachines=computed(()=>machinesData.filter(m=>names.value.includes(String(m.Manufacturer||'').toLowerCase())&&Number(m.Sold||0)===0&&Number(m.Off_Market??m.OffMarket??0)===0&&Number(m.dont_advertise||0)===0&&/lathe|turning/i.test(`${m.Groups||''} ${m.WebDesc||''}`)).slice(0,8))
function machineSlug(m){return `${m.Manufacturer}-${m.Model}`.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
function yearRange(e){const ys=e.records.map(r=>Number(r.year)).filter(y=>y>1900).sort((a,b)=>a-b);if(!ys.length)return 'Year varies';return ys[0]===ys.at(-1)?String(ys[0]):`${ys[0]}–${ys.at(-1)}`}
useSeoMeta({title:()=>`${props.manufacturer} CNC Lathe Specifications & Machines for Sale | UMS`,description:()=>`Browse historical ${props.manufacturer} CNC lathe specifications by exact model and year, plus current machines available from Used Machinery Source.`})
useHead({link:[{rel:'canonical',href:()=>`https://usedmachinerysource.com/spec-library/${props.routeSlug}/cnc-lathes`}]})
</script>
<style scoped>.library{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1180px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:46px 0;border-bottom:4px solid #f47b20}.back{color:#c8d9eb;text-decoration:none}.kicker,.eyebrow{color:#f47b20;font-size:.76rem;font-weight:900;letter-spacing:.12em;margin:18px 0 7px}.hero h1{font-size:clamp(2rem,4vw,3.15rem);margin:0 0 12px}.hero p{max-width:850px;line-height:1.7}.body{padding-top:38px}.current,.browse{margin-bottom:42px}.current h2,.browse h2{margin:0 0 10px;color:#0b2545}.intro{color:#526579;line-height:1.65;max-width:900px}.current-grid,.model-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-top:18px}.current-card,.model-card{border:1px solid #d8e0e8;border-radius:8px;padding:16px;text-decoration:none;color:#17273a;background:#fff;display:flex;flex-direction:column;gap:6px;box-shadow:0 2px 8px rgba(0,0,0,.04)}.current-card:hover,.model-card:hover{border-color:#1c4587;box-shadow:0 4px 12px rgba(0,0,0,.08)}.current-card span,.model-card span{color:#526579;font-size:.9rem}.current-card small,.model-card small{color:#718096}.search{width:100%;max-width:520px;border:1px solid #b8c4d0;border-radius:6px;padding:12px 14px;font-size:1rem;margin:10px 0 4px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;border-radius:6px;margin:36px 0}.cta{background:#0b2545;color:#fff;border-top:5px solid #f47b20;border-radius:9px;padding:28px}.cta h2{margin:0 0 8px}.cta p{margin:0 0 16px}.cta a{display:inline-block;background:#f47b20;color:#fff;text-decoration:none;font-weight:800;padding:11px 16px;border-radius:5px}.empty{padding:20px 0;color:#526579}@media(max-width:950px){.current-grid,.model-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:720px){.wrap{padding:0 18px}.current-grid,.model-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.current-grid,.model-grid{grid-template-columns:1fr}}</style>
