<template><div><article v-for="c in configurations" :key="c.title" class="configuration"><div class="config-head"><div><div class="year">{{ clean(c.year) }} <span class="year-model">{{ clean(model) }}</span></div><h3>{{ clean(c.title) }}</h3><p><strong>Control:</strong> {{ clean(c.control) }}</p></div><button type="button" class="copy" @click="copySpecs(c)">{{ copied===c.title ? 'Copied!' : 'Copy Specifications' }}</button></div><div v-if="c.specs?.length" class="spec-grid"><div v-for="(s,index) in c.specs" :key="`${s.label}-${index}`" class="spec"><span>{{ clean(s.label) }}</span><strong>{{ clean(s.value) }}</strong></div></div><div v-if="c.recordedSpecs" class="recorded"><span>Recorded specifications</span><p>{{ clean(c.recordedSpecs) }}</p></div><p v-if="c.note" class="note">{{ clean(c.note) }}</p></article></div></template>
<script setup>
import { ref } from 'vue'
import { cleanSpecText } from '~/utils/specText'
const props=defineProps({model:{type:String,required:true},configurations:{type:Array,required:true}})
const copied=ref('')
const clean=cleanSpecText
async function copySpecs(c){const lines=[`${clean(props.model)} - ${clean(c.year)}`,`Control: ${clean(c.control)}`,...(c.specs||[]).map(s=>`${clean(s.label)}: ${clean(s.value)}`)];if(c.recordedSpecs)lines.push(`Recorded specifications: ${clean(c.recordedSpecs)}`);if(c.note)lines.push(clean(c.note));try{await navigator.clipboard.writeText(lines.filter(Boolean).join('\n'));copied.value=c.title;setTimeout(()=>{if(copied.value===c.title)copied.value=''},1800)}catch{copied.value=''}}
</script>
<style scoped>.configuration{border:1px solid #cfd9e3;border-radius:10px;padding:24px;margin:24px 0;background:#fff}.config-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.config-head h3{font-size:1.35rem;color:#0b2545;margin:4px 0 6px}.config-head p{margin:0}.year{font-size:.82rem;font-weight:900;letter-spacing:.06em;color:#1c4587}.year-model{margin-left:8px;color:#0b2545;letter-spacing:0}.copy{border:0;border-radius:6px;background:#1c4587;color:#fff;font-weight:800;padding:11px 16px;cursor:pointer;white-space:nowrap}.spec-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:20px}.spec{border:1px solid #d7e0e8;border-radius:8px;padding:15px;background:#f8fafc}.spec span,.recorded span{display:block;color:#657688;font-size:.76rem;text-transform:uppercase;font-weight:800;margin-bottom:6px}.spec strong{color:#0b2545}.recorded{margin-top:20px;border:1px solid #d7e0e8;border-radius:8px;padding:16px;background:#f8fafc}.recorded p{margin:0;color:#0b2545;line-height:1.65}.note{color:#53677a;line-height:1.55;margin-bottom:0}@media(max-width:760px){.spec-grid{grid-template-columns:1fr}.config-head{display:block}.copy{margin-top:14px}.year-model{display:inline}}</style>