<template><div><article v-for="c in configurations" :key="c.title" class="configuration"><div class="config-head"><div><h3>{{ clean(c.title) }}</h3><p><strong>Control:</strong> {{ clean(c.control)||'Not recorded' }}</p></div><button type="button" class="copy" @click="copySpecs(c)">{{ copied===c.title ? 'Copied!' : 'Copy specs' }}</button></div><table v-if="rows(c).length" class="spec-table"><tbody><template v-for="(s,index) in rows(c)" :key="index"><tr v-if="s.section" class="section-row"><th colspan="2">{{s.section}}</th></tr><tr v-else-if="s.equipment" class="equipment-row"><td colspan="2">{{s.value}}</td></tr><tr v-else><th>{{s.label}}</th><td>{{s.value}}</td></tr></template></tbody></table><p v-if="c.note" class="note">{{ clean(c.note) }}</p></article></div></template>
<script setup>
import { ref } from 'vue'
import { cleanSpecText } from '~/utils/specText'
const props=defineProps({model:{type:String,required:true},configurations:{type:Array,required:true}})
const copied=ref(''),clean=cleanSpecText
function parsedRecorded(text){const parts=clean(text).split(',').map(x=>x.trim()).filter(Boolean);const rules=[[/swing/i,'Swing'],[/centers?/i,'Distance Between Centers'],[/spindle (bore|hole)/i,'Spindle Bore'],[/\brpm\b/i,'Maximum Spindle Speed'],[/\bhp\b/i,'Main Motor (HP)'],[/turret/i,'Turret'],[/chuck/i,'Chuck'],[/tool eye|tool presetter/i,'Tool Presetter'],[/tailstock/i,'Tailstock'],[/chip conv/i,'Chip Conveyor'],[/live tooling/i,'Live Tooling'],[/barfeed/i,'Barfeed'],[/\batc\b/i,'Automatic Tool Changer'],[/\bx\s/i,'X-Axis Travel'],[/\by\s/i,'Y-Axis Travel'],[/\bz\s/i,'Z-Axis Travel']];return parts.map((value,i)=>{const hit=rules.find(([re])=>re.test(value));return{label:hit?hit[1]:(i===0?'Recorded Specification':'Equipment / Feature'),value}})}
function rows(c){const out=[],eq=[];let lastGroup='';for(const s of (c.specs||[])){const label=clean(s.label||s.description),value=clean(s.value||s.specvalues),group=clean(s.group||s.groupname||s.groupnames);if(!label||!value)continue;if(/^(equipped with|equipment)$/i.test(label)){eq.push(value);continue}if(group&&group!==lastGroup){out.push({section:group.replace(/:$/,'')});lastGroup=group}out.push({label,value})}if(c.recordedSpecs&&!out.length)out.push(...parsedRecorded(c.recordedSpecs));for(const value of (c.equippedWith||[])){const v=clean(value);if(v)eq.push(v)}const unique=[...new Set(eq)];if(unique.length){out.push({section:'Equipped With'});out.push(...unique.map(value=>({equipment:true,value})))}return out}
async function copySpecs(c){const lines=[clean(c.title),`Control: ${clean(c.control)||'Not recorded'}`,...rows(c).map(s=>`${s.label}: ${s.value}`)];if(c.note)lines.push(clean(c.note));try{await navigator.clipboard.writeText(lines.filter(Boolean).join('\n'));copied.value=c.title;setTimeout(()=>{if(copied.value===c.title)copied.value=''},1800)}catch{copied.value=''}}
</script>
<style scoped>.configuration{border:1px solid #cfd9e3;border-radius:8px;padding:24px;margin:24px 0 34px;background:#fff}.config-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:18px}.config-head h3{font-size:1.35rem;color:#0b2545;margin:0 0 7px}.config-head p{margin:0;color:#53677a}.copy{border:0;border-radius:5px;background:#0b2545;color:#fff;font-weight:800;padding:10px 14px;cursor:pointer;white-space:nowrap}.spec-table{width:100%;border-collapse:collapse;border-top:1px solid #d7e0e8}.spec-table th,.spec-table td{padding:10px 12px;border-bottom:1px solid #d7e0e8;text-align:left;vertical-align:top}.spec-table th{width:35%;font-weight:800;color:#0b2545;background:#f7f9fb}.spec-table td{color:#17273a}.section-row th{width:auto;background:#eaf0f6;color:#0b2545;font-size:1rem;padding:11px 12px;border-top:2px solid #c7d3df}.equipment-row td{padding:7px 12px 7px 24px}.note{color:#53677a;line-height:1.55;margin:18px 0 0}@media(max-width:760px){.config-head{display:block}.copy{margin-top:14px}.spec-table th{width:42%}}</style>