<template><main class="page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/manufacturers" class="back">← Manufacturers</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>{{manufacturer}} Specifications</h1><p>Historical {{manufacturer}} machines organized by machine type and model.</p></div></section><section class="wrap section"><div v-for="type in types" :key="type.name" class="type"><h2>{{type.name}}</h2><div class="models"><NuxtLink v-for="model in type.models" :key="model" :to="modelRoute(manufacturer,model,type.name)" class="model">{{model}}</NuxtLink></div></div></section></main></template><script setup>
import historicalMachines from '~/assets/data/historical-machines.json'
const clean=s=>String(s||'').trim()
const slug=s=>clean(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const rows=historicalMachines.filter(m=>clean(m.Manufacturer)&&clean(m.Model)&&clean(m.WebDesc||m.Web_Desc))
const route=useRoute()
const manufacturer=[...new Set(rows.map(m=>clean(m.Manufacturer)))].find(m=>slug(m)===String(route.params.manufacturer||''))
if(!manufacturer)throw createError({statusCode:404,statusMessage:'Manufacturer not found'})
const mine=rows.filter(m=>clean(m.Manufacturer)===manufacturer)
const types=[...new Set(mine.map(m=>clean(m.WebDesc||m.Web_Desc)))].sort((a,b)=>a.localeCompare(b)).map(name=>({name,models:[...new Set(mine.filter(m=>clean(m.WebDesc||m.Web_Desc)===name).map(m=>clean(m.Model)))].sort((a,b)=>a.localeCompare(b))}))
const modelRoute=(m,model,type)=>{const ms=slug(m),mo=slug(model),t=type.toLowerCase();if(t.startsWith('cnc lathes'))return '/spec-library/'+ms+'/'+mo;if(t.startsWith('cnc machining centers, vertical'))return '/spec-library/'+ms+'/vmcs/'+mo;if(t.startsWith('cnc machining centers, horizontal'))return '/spec-library/'+ms+'/hmcs/'+mo;return '/spec-library/manufacturers/'+ms+'?model='+encodeURIComponent(model)}
useSeoMeta({title:manufacturer+' Machine Specifications | UMS Spec Library',description:'Historical '+manufacturer+' machine specifications organized by machine type and model.'})
</script><style scoped>.page{color:#17273a;padding-bottom:60px}.wrap{max-width:1200px;margin:auto;padding:0 28px}.hero{background:#0b2545;color:#fff;padding:46px 0;border-bottom:4px solid #f47b20}.back{color:#c8d9eb}.kicker{color:#f47b20;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:16px 0 8px}.hero h1{font-size:3rem;margin:0 0 10px}.section{padding-top:34px}.type{margin-bottom:36px}.type h2{color:#0b2545;border-bottom:2px solid #f47b20;padding-bottom:8px}.models{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.model{padding:11px;border:1px solid #d7e0e8;border-radius:6px;text-decoration:none;color:#1c4587;font-weight:700}@media(max-width:800px){.models{grid-template-columns:repeat(2,1fr)}.wrap{padding:0 18px}}</style>