<template>
  <main class="page">
    <section class="page-hero"><div class="wrap"><p class="eyebrow">OUR SERVICES</p><h1>Machinery Solutions Built Around Your Needs.</h1><p>Whether you need to buy a machine, sell surplus equipment or locate something specific, Used Machinery Source can help.</p></div></section>

    <section class="section"><div class="wrap service-grid">
      <article class="service-card"><h2>Buying Used CNC Machinery</h2><p>Search our current inventory of quality used CNC machinery. We provide detailed specifications, photos and machine information to help you evaluate equipment before making a decision.</p><ul><li>CNC machining centers</li><li>CNC lathes and turning centers</li><li>Boring mills, VTLs, grinders and more</li><li>Equipment located throughout the United States</li></ul><NuxtLink to="/equipment" class="action">Search Equipment →</NuxtLink></article>
      <article class="service-card"><h2>Locating the Machine You Need</h2><p>Not every good machine is publicly advertised. Tell us your requirements and we can use our industry contacts to help identify equipment that fits your application.</p><ul><li>Specific manufacturers and models</li><li>Capacity and specification requirements</li><li>Replacement or expansion machinery</li><li>Hard-to-find equipment</li></ul><NuxtLink to="/equipment#tell-us-what-you-need" class="action">Tell Us What You Need →</NuxtLink></article>
      <article class="service-card"><h2>Selling Surplus Machinery</h2><p>We help manufacturers move machinery they no longer need. From a single machine to surplus equipment or a larger facility project, we can help present the equipment to the right audience.</p><ul><li>Single machines</li><li>Surplus and trade-in equipment</li><li>Multiple-machine packages</li><li>Plant and facility liquidations</li></ul><NuxtLink to="/sell-your-machine" class="action">Sell Your Machine →</NuxtLink></article>
    </div></section>

    <section class="process"><div class="wrap"><p class="eyebrow dark">HOW WE WORK</p><h2>Clear. Responsive. Straightforward.</h2><div class="steps"><div><strong>1</strong><h3>Tell Us the Need</h3><p>Send the machine requirements or equipment you have available.</p></div><div><strong>2</strong><h3>We Review the Details</h3><p>We evaluate the information and determine the best next step.</p></div><div><strong>3</strong><h3>We Get to Work</h3><p>We market, source or coordinate the opportunity based on your needs.</p></div></div></div></section>

    <section class="cta"><div class="wrap cta-inner"><div><h2>Ready to Get Started?</h2><p>Tell us what you need and we’ll take it from there.</p></div><NuxtLink to="/contact" class="btn">Contact Used Machinery Source</NuxtLink></div></section>
  </main>
</template>

<script setup>
useSeoMeta({title:'Used CNC Machinery Services | Used Machinery Source',description:'Used Machinery Source helps manufacturers buy, sell and locate used CNC machinery, surplus equipment and plant machinery.'})
</script>

<style scoped>
.page{color:#1a2532}.wrap{max-width:1280px;margin:0 auto;padding-left:40px;padding-right:40px}.page-hero{background:#061526;color:#fff;padding:78px 0}.eyebrow{margin:0 0 14px;color:#f36c21;font-size:14px;font-weight:800;letter-spacing:1.5px}.eyebrow.dark{color:#d75b16}.page-hero h1{max-width:900px;font-size:clamp(42px,5vw,62px);line-height:1.05;margin:0 0 20px}.page-hero p:last-child{max-width:780px;font-size:20px;line-height:1.6;color:#dce4ed}.section{padding:75px 0}.service-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:25px}.service-card{border:1px solid #dfe4e9;border-top:4px solid #f36c21;padding:36px;background:#fff;box-shadow:0 10px 25px rgba(20,40,60,.05)}.service-card h2{color:#082b5c;font-size:25px;line-height:1.2;margin:12px 0 18px}.service-card p,.service-card li{color:#4a5460;line-height:1.65;font-size:16px}.service-card ul{padding-left:20px;margin:20px 0}.action{color:#082b5c;font-weight:800;text-decoration:none}.action:hover{color:#f36c21}.process{background:#f4f6f8;padding:70px 0}.process h2{color:#082b5c;font-size:36px;margin:0 0 35px}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:40px}.steps strong{display:flex;width:45px;height:45px;border-radius:50%;background:#082b5c;color:#fff;align-items:center;justify-content:center}.steps h3{color:#082b5c;font-size:21px;margin:16px 0 8px}.steps p{color:#56606b;line-height:1.6}.cta{background:#0b315f;color:#fff;padding:45px 0}.cta-inner{display:flex;align-items:center;justify-content:space-between;gap:30px}.cta h2{margin:0 0 8px;font-size:30px}.cta p{margin:0;color:#dce5ef}.btn{background:#f36c21;color:#fff;display:inline-flex;min-height:52px;padding:0 24px;align-items:center;text-decoration:none;font-weight:800;border-radius:3px}
@media(max-width:900px){.service-grid,.steps{grid-template-columns:1fr}.wrap{padding-left:22px;padding-right:22px}.cta-inner{align-items:flex-start;flex-direction:column}.page-hero{padding:55px 0}}
</style>
