<template>
<main class="page"><section class="hero"><p class="eyebrow">UMS MACHINERY SPECIFICATION LIBRARY</p><h1>Haas CNC Lathes & Turning Centers</h1><p>Research historical Haas CNC lathe specifications by exact model designation, and see Haas turning machines currently offered by Used Machinery Source.</p></section>
<section><h2>Haas CNC Lathes Currently for Sale</h2><p class="section-intro">Current inventory is kept separate from the historical specification library below.</p><div v-if="current.length" class="current-grid"><article v-for="m in current" :key="m.InvID" class="current-card"><p class="badge">FOR SALE NOW</p><h3>{{ m.Year }} Haas {{ m.Model }}</h3><p>{{ m.AdvSpec || m.Adv_Spec }}</p><NuxtLink :to="machineUrl(m)">View Machine →</NuxtLink></article></div><div v-else class="empty">We do not currently have an advertised Haas CNC lathe available. <NuxtLink to="/wanted">Tell us what Haas machine you need.</NuxtLink></div></section>
<section><h2>Browse Haas CNC Lathe Families</h2><div class="families"><div><h3>ST Series</h3><p>Modern Haas turning centers including standard, Y-axis, live-tool, Super Speed, big-bore and long-bed configurations.</p></div><div><h3>SL Series</h3><p>Earlier Haas production turning centers with standard, big-bore, long-bed and live-tool variants.</p></div><div><h3>TL Series</h3><p>Haas Toolroom Lathes and related historical TL turning configurations.</p></div><div><h3>HL / DS / CL</h3><p>Earlier HL turning centers plus dual-spindle DS and compact CL configurations recorded in the UMS library.</p></div></div></section>
<section><h2>Haas CNC Lathe Specification Library</h2><p class="section-intro">The UMS historical database contains {{ recordCount }} Haas CNC lathe records across {{ models.length }} exact model designations. Original model wording is preserved; similar-looking model names are not automatically combined.</p><input v-model="query" class="search" type="search" placeholder="Search Haas model — e.g. SL-30T, ST-30, TL-3B"><div class="model-grid"><NuxtLink v-for="m in filtered" :key="m.slug" :to="`/spec-library/haas/${m.slug}`" class="model-card"><strong>Haas {{ m.model }}</strong><span>{{ m.records.filter(r=>r.summary?.trim()).length }} historical configuration{{ m.records.filter(r=>r.summary?.trim()).length===1?'':'s' }}</span></NuxtLink></div></section>
<section class="note"><h2>About these specifications</h2><p>These are historical UMS machinery records, not universal factory specifications and not current availability claims. Capacities and equipment can vary by model year, configuration and options. Each model page identifies the year and recorded control/configuration whenever that information exists.</p></section>
</main></template>
<script setup>
import machines from '~/assets/data/machines.json'
import p1 from '~/assets/data/haasHistoricalModels1.json';import p2 from '~/assets/data/haasHistoricalModels2.json';import p3 from '~/assets/data/haasHistoricalModels3.json';import p4 from '~/assets/data/haasHistoricalModels4.json'
const query=ref(''); const all=[...p1,...p2,...p3,...p4]; const models=computed(()=>all.filter(x=>x.records.some(r=>r.summary?.trim())).sort((a,b)=>a.model.localeCompare(b.model))); const recordCount=computed(()=>all.reduce((n,x)=>n+x.records.length,0)); const filtered=computed(()=>{const q=query.value.trim().toLowerCase();return q?models.value.filter(x=>x.model.toLowerCase().includes(q)):models.value})
const current=computed(()=>machines.filter(m=>String(m.Manufacturer||'').toLowerCase()==='haas' && String(m.Groups||'').includes('CNC Lathes') && Number(m.Sold||0)===0 && Number(m.OffMarket??m.Off_Market??0)===0 && Number(m.dont_advertise||0)===0))
function machineUrl(m){const slug=`${m.Manufacturer||''}-${m.Model||''}`.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return `/equipment/${m.InvID}/${slug}`}
useSeoMeta({title:'Used Haas CNC Lathes | Specifications & Machines for Sale | UMS',description:'Browse Haas CNC lathe specifications by exact model and see current used Haas turning centers for sale from Used Machinery Source.'});useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/haas/cnc-lathes'}]})
</script>
<style scoped>.page{max-width:1280px;margin:0 auto;padding:42px 28px 72px;color:#172033}.hero{padding-bottom:28px;border-bottom:1px solid #dde3ea}.eyebrow{font-size:13px;font-weight:800;letter-spacing:.12em;color:#647184}.hero h1{font-size:44px;color:#0b2545;margin:8px 0 14px}.hero p,.section-intro{font-size:18px;line-height:1.55;max-width:900px}section{margin:38px 0}h2{font-size:29px;color:#0b2545}.current-grid,.families{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.current-card,.families>div{border:1px solid #dbe1e8;border-radius:9px;padding:20px}.badge{font-size:12px;font-weight:900;color:#18713b}.current-card a,.empty a{color:#1c4587;font-weight:800}.empty{background:#f3f6fa;padding:20px;border-radius:8px}.families{grid-template-columns:repeat(4,1fr)}.families h3{margin-top:0}.search{width:100%;max-width:620px;padding:13px 15px;border:1px solid #aeb8c4;border-radius:6px;font-size:17px;margin:8px 0 20px}.model-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.model-card{border:1px solid #dbe1e8;border-radius:7px;padding:14px;text-decoration:none;color:#172033;display:flex;flex-direction:column;gap:6px}.model-card:hover{border-color:#1c4587;background:#f5f8fc}.model-card span{font-size:13px;color:#687586}.note{background:#f2f6fb;border-left:4px solid #1c4587;padding:20px 24px}.note h2{margin-top:0}@media(max-width:900px){.model-grid{grid-template-columns:repeat(2,1fr)}.families,.current-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.page{padding:30px 18px 55px}.hero h1{font-size:34px}.model-grid,.families,.current-grid{grid-template-columns:1fr}}</style>