<template>
  <main class="library-page">
    <section class="hero"><div class="wrap"><NuxtLink to="/spec-library/cnc-lathes" class="back-link">← CNC Lathe Spec Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Haas CNC Lathes & Turning Centers</h1><p>Research Haas CNC lathe and turning-center families, exact model designations and historical specifications from machinery records accumulated over many years by Used Machinery Source.</p><div class="hero-actions"><a href="#haas-models" class="hero-primary">Browse Haas Specifications</a><NuxtLink to="/equipment" class="hero-secondary">View CNC Lathes for Sale</NuxtLink></div></div></section>

    <section class="wrap section current"><div class="kicker sale">FOR SALE NOW</div><h2>Haas CNC Lathes Currently Available</h2><div v-if="current.length" class="current-grid"><article v-for="m in current" :key="m.InvID" class="current-card"><h3>{{ m.Year }} {{ m.Manufacturer }} {{ m.Model }}</h3><p>{{ webDescription(m) }}</p><p class="stock">Stock #{{ m.InvID }}</p><NuxtLink :to="machineUrl(m)" class="button">View Machine</NuxtLink></article></div><div v-else class="notice"><strong>No matching Haas CNC lathe is listed in current inventory right now.</strong> The Spec Library below remains available for research. <NuxtLink to="/equipment#tell-us-what-you-need">Tell us what you need →</NuxtLink></div></section>

    <section class="section muted"><div class="wrap"><div class="kicker">HAAS MODEL FAMILIES</div><h2>Browse Haas Turning Equipment</h2><p class="intro">UMS historical records include SL, ST, TL, HL, DS, CL and other Haas turning platforms. Original model wording is preserved because similar-looking designations can represent different spindle sizes, bed lengths, live-tool packages, Y-axis configurations, sub-spindles or production generations.</p><div class="family-grid">
      <article class="family-card featured"><h3>ST Series</h3><p>Modern Haas turning centers including standard, big-bore, live-tool, Y-axis, long-bed and sub-spindle configurations recorded in UMS history.</p><div class="model-links"><NuxtLink v-for="m in familyModels('ST')" :key="m.slug" :to="`/spec-library/haas/${m.slug}`" class="text-link">{{ m.model }} specifications →</NuxtLink></div></article>
      <article class="family-card featured"><h3>SL Series</h3><p>Earlier Haas production turning centers with standard, big-bore, long-bed and live-tool variants spanning many years.</p><div class="model-links"><NuxtLink v-for="m in familyModels('SL')" :key="m.slug" :to="`/spec-library/haas/${m.slug}`" class="text-link">{{ m.model }} specifications →</NuxtLink></div></article>
      <article class="family-card featured"><h3>TL Series</h3><p>Haas Toolroom Lathes and related TL turning configurations used for lower-volume work, prototyping and general machining.</p><div class="model-links"><NuxtLink v-for="m in familyModels('TL')" :key="m.slug" :to="`/spec-library/haas/${m.slug}`" class="text-link">{{ m.model }} specifications →</NuxtLink></div></article>
      <article class="family-card featured"><h3>HL / DS / CL</h3><p>Earlier HL turning centers plus dual-spindle DS and compact CL configurations represented in the UMS historical database.</p><div class="model-links"><NuxtLink v-for="m in otherFamilyModels" :key="m.slug" :to="`/spec-library/haas/${m.slug}`" class="text-link">{{ m.model }} specifications →</NuxtLink></div></article>
    </div></div></section>

    <section id="haas-models" class="wrap section"><div class="kicker">HAAS SPECIFICATION LIBRARY</div><h2>Browse Exact Haas CNC Lathe Models</h2><p class="intro">The UMS historical database contains {{ recordCount }} Haas CNC lathe records across {{ all.length }} exact model designations. {{ models.length }} model pages have usable recorded specification summaries. Similar-looking model names are not automatically combined.</p><input v-model="query" class="search" type="search" placeholder="Search Haas model — e.g. SL-30T, ST-30, TL-3B"><div class="additional-grid"><NuxtLink v-for="m in filtered" :key="m.slug" :to="`/spec-library/haas/${m.slug}`" class="additional-link"><strong>{{ m.model }}</strong><span>{{ usableCount(m) }} historical configuration{{ usableCount(m)===1?'':'s' }}</span></NuxtLink></div></section>

    <section class="wrap section history"><div class="history-label">SPECIFICATION LIBRARY — HISTORICAL INFORMATION</div><h2>How to Use the Haas Spec Library</h2><p>These pages are intended for machinery buyers, dealers and manufacturing professionals researching older Haas CNC lathes. Historical records are not current inventory and do not mean a machine is available for sale.</p><p><strong>Specifications can vary by year, spindle size, control generation, bed length, tooling package and optional equipment.</strong> For that reason, UMS keeps materially different Haas model designations separate and displays the exact model with each historical year record.</p></section>
  </main>
</template>
<script setup>
import machinesData from '~/assets/data/machines.json'
import p1 from '~/assets/data/haasHistoricalModels1.json'
import p2 from '~/assets/data/haasHistoricalModels2.json'
import p3 from '~/assets/data/haasHistoricalModels3.json'
import p4 from '~/assets/data/haasHistoricalModels4.json'
const query=ref('')
const all=[...p1,...p2,...p3,...p4]
const usableCount=m=>m.records.filter(r=>r.summary?.trim()).length
const models=computed(()=>all.filter(m=>usableCount(m)>0).sort((a,b)=>a.model.localeCompare(b.model)))
const recordCount=computed(()=>all.reduce((n,m)=>n+m.records.length,0))
const filtered=computed(()=>{const q=query.value.trim().toLowerCase();return q?models.value.filter(m=>m.model.toLowerCase().includes(q)):models.value})
const familyModels=prefix=>models.value.filter(m=>m.model.toUpperCase().startsWith(`${prefix}-`)||m.model.toUpperCase().startsWith(`${prefix} `)).slice(0,12)
const otherFamilyModels=computed(()=>models.value.filter(m=>/^(HL|DS|CL)[- ]/i.test(m.model)).slice(0,14))
const webDescription=m=>m.WebDesc||m.Web_Desc||m.AdvSpec||m.Adv_Spec||''
const offMarket=m=>m.OffMarket??m.Off_Market??0
const current=computed(()=>(machinesData||[]).filter(m=>Number(m.Sold)===0&&Number(offMarket(m))===0&&Number(m.dont_advertise||0)===0&&String(m.Groups||'').includes('CNC Lathes')&&String(m.Manufacturer||'').trim().toLowerCase()==='haas').sort((a,b)=>Number(b.Year||0)-Number(a.Year||0)))
const machineUrl=m=>`/equipment/${m.InvID}/${`${m.Manufacturer||''}-${m.Model||''}`.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}`
useSeoMeta({title:'Used Haas CNC Lathes | Specifications & Machines for Sale | UMS',description:'Browse Haas CNC lathe specifications by exact model and see current used Haas turning centers for sale from Used Machinery Source.'})
useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/haas/cnc-lathes'}]})
</script>
<style scoped>
.library-page{color:#17273a;background:#fff;padding-bottom:64px}.wrap{max-width:1260px;margin:0 auto;padding-left:28px;padding-right:28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:50px 0;border-bottom:4px solid #f47b20}.back-link{color:#c8d9eb;text-decoration:none}.kicker{font-size:.78rem;font-weight:800;letter-spacing:.12em;color:#1c5a94;margin:18px 0 8px}.hero .kicker{color:#f47b20}.sale{color:#b44c10}.hero h1{font-size:clamp(2rem,4vw,3.25rem);margin:0 0 14px}.hero p{max-width:850px;font-size:1.08rem;line-height:1.7}.hero-actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:22px}.hero-actions a{display:inline-block;padding:11px 16px;border-radius:5px;text-decoration:none;font-weight:800}.hero-primary{background:#f47b20;color:#fff}.hero-secondary{border:1px solid #b8cadc;color:#fff}.section{padding-top:46px;padding-bottom:46px}.section h2{font-size:2rem;margin:0 0 14px}.intro{max-width:980px;line-height:1.7}.muted{background:#f4f7fa}.current-grid,.family-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin-top:24px}.current-card,.family-card,.notice{border:1px solid #d8e0e8;border-radius:12px;padding:22px;background:#fff}.current-card h3,.family-card h3{color:#0b2545;margin-top:0}.current-card p{line-height:1.55}.stock{color:#667789}.button{display:inline-block;background:#1c4587;color:#fff;text-decoration:none;padding:10px 16px;border-radius:6px;font-weight:700}.notice a,.text-link{color:#1c4587;font-weight:800;text-decoration:none}.text-link:hover{text-decoration:underline}.family-card.featured{border-top:4px solid #f47b20}.family-card p{line-height:1.6;color:#526579}.model-links{display:flex;flex-direction:column;gap:8px}.search{width:100%;max-width:620px;padding:13px 15px;border:1px solid #aeb8c4;border-radius:6px;font-size:17px;margin:8px 0 22px}.search:focus{outline:2px solid #f47b20;outline-offset:1px}.additional-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px 18px;margin-top:24px}.additional-link{border:1px solid #d7e0e8;border-radius:8px;padding:12px 14px;text-decoration:none;color:#17273a;background:#fff;display:flex;flex-direction:column;gap:5px}.additional-link:hover{border-color:#f47b20;background:#fff9f4}.additional-link strong{color:#0b2545}.additional-link span{font-size:.82rem;color:#6a7888}.history{margin-top:42px;border:2px solid #9fb4c8;border-left:5px solid #f47b20;border-radius:14px;padding-top:30px;padding-bottom:30px}.history-label{font-weight:900;color:#8c3f10;letter-spacing:.08em;font-size:.8rem}.history p{line-height:1.7}@media(max-width:850px){.current-grid,.family-grid,.additional-grid{grid-template-columns:1fr}.wrap{padding-left:18px;padding-right:18px}.hero{padding:36px 0}.section{padding-top:34px;padding-bottom:34px}}
</style>