<template><main class="model-page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak Dual Turn 20 Specifications</h1><p>Historical Dual Turn 20 twin-spindle/twin-turret specifications organized by year and control from UMS machinery records.</p></div></section><section class="wrap section"><div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> Specifications may vary by individual machine, automation package and equipment.</div><h2>Historical Dual Turn 20 Specifications by Year</h2><p>UMS records show the Dual Turn 20 as an opposing-spindle, twin-turret production turning platform, with a control transition from T-PLUS to Fusion 640T in later records.</p><SpecYearConfigurations model="Mazak Dual Turn 20" :configurations="configurations" /></section></main></template>
<script setup>
const configurations=[
{year:'1995',title:'1995 Mazak Dual Turn 20',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Maximum machining diameter',value:'12.6 in'},{label:'Spindle hole',value:'2.4 in'},{label:'Maximum spindle speed',value:'4,750 RPM'},{label:'Spindles',value:'Twin opposing spindles'},{label:'Turrets',value:'Twin turrets'},{label:'Equipment',value:'Unload package'}]},
{year:'1996',title:'1996 Mazak Dual Turn 20',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing / machining diameter',value:'12.6 in in UMS records'},{label:'Spindle hole',value:'2.4 in'},{label:'Maximum spindle speed',value:'4,750 RPM'},{label:'Spindles',value:'Twin opposing spindles'},{label:'Turrets',value:'Twin turrets'},{label:'Equipment',value:'Load / unload package'}],note:'Two 1996 UMS records support this general configuration.'},
{year:'1997',title:'1997 Mazak Dual Turn 20',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'12.6 in'},{label:'Distance between centers',value:'24 in on detailed record'},{label:'Spindle bore',value:'2.4 in on recorded machine'},{label:'Maximum spindle speed',value:'4,750 RPM on recorded machine'},{label:'Main motor',value:'20 HP on detailed record'},{label:'Spindles',value:'Twin opposing spindles'},{label:'Turrets',value:'2 × 12 positions on detailed record'},{label:'Equipment',value:'Chip conveyor; tool eye on detailed record'}]},
{year:'1998',title:'1998 Mazak Dual Turn 20',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'12.6 in'},{label:'Spindle hole',value:'2.4 in'},{label:'Maximum spindle speed',value:'4,750–5,000 RPM in UMS records'},{label:'Main motor',value:'20 HP on recorded machine'},{label:'Spindles',value:'Twin opposing spindles'},{label:'Turrets',value:'2 × 12 positions on recorded machine'},{label:'Equipment',value:'Unload package; LNS barfeed on one record'}]},
{year:'2000',title:'2000 Mazak Dual Turn 20',control:'Mazatrol Fusion 640T',specs:[{label:'Swing',value:'12.6 in'},{label:'Spindle hole',value:'2.4 in'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Main motor',value:'20 HP'},{label:'Spindles',value:'Twin opposing spindles'},{label:'Turrets',value:'2 × 12 positions'},{label:'Automation',value:'Gantry loader'},{label:'Equipment',value:'Conveyor'}]}]
useSeoMeta({title:'Mazak Dual Turn 20 Specifications by Year | UMS Spec Library',description:'Historical Mazak Dual Turn 20 twin-spindle CNC lathe specifications organized by year, control and configuration from UMS machinery records.'});useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/dual-turn-20'}]})
</script>
<style scoped>.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.hero p{max-width:820px;line-height:1.7}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;border-radius:6px;margin-bottom:34px}.section h2{color:#0b2545;margin:34px 0 12px}.section>p{line-height:1.7;max-width:920px}@media(max-width:760px){.wrap{padding:0 18px}}</style>