<template><main class="model-page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak Integrex 200SY Specifications</h1><p>Historical Mazak Integrex 200SY mill-turn specifications organized by year and control from UMS machinery records.</p></div></section><section class="wrap section"><div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> Specifications may vary by year, control, configuration and optional equipment.</div><h2>Historical Integrex 200SY Specifications by Year</h2><SpecYearConfigurations model="Mazak Integrex 200SY" :configurations="configurations" /></section></main></template>
<script setup>
const configurations=[
{year:'1999',title:'1999 Mazak Integrex 200SY — Fusion 640T',control:'Mazatrol Fusion 640T / CRT',specs:[{label:'Swing',value:'21.25 in'},{label:'Spindle bore',value:'2.4 in'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Main motor',value:'30 HP'},{label:'ATC',value:'80 tools on recorded machines'},{label:'Equipment',value:'Sub-spindle and live tooling'}],note:'Multiple 1999 UMS records show this general configuration; one includes an LNS barfeed.'},
{year:'1999',title:'1999 Mazak Integrex 200SY — Fusion 640MT',control:'Mazatrol Fusion 640MT',specs:[{label:'Swing',value:'21.2 in'},{label:'Spindle hole',value:'2.4 in'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Equipment',value:'Sub-spindle, milling, chip conveyor'}],note:'UMS keeps this control/configuration separate from the 640T records rather than assuming they are identical.'},
{year:'2000',title:'2000 Mazak Integrex 200SY',control:'Mazatrol Fusion 640MT',specs:[{label:'Swing',value:'21 in'},{label:'Spindle hole',value:'2.4 in'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Equipment',value:'Sub-spindle, live tooling, Y-axis, LNS Quick Load Servo barfeed'}]}
]
useSeoMeta({title:'Mazak Integrex 200SY Specifications by Year | UMS Spec Library',description:'Historical Mazak Integrex 200SY mill-turn specifications organized by year, control and configuration from UMS machinery records.'});useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/integrex-200sy'}]})
</script>
<style scoped>.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.hero p{max-width:820px;line-height:1.7}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;border-radius:6px;margin-bottom:34px}.section h2{color:#0b2545;margin:34px 0 12px}@media(max-width:760px){.wrap{padding:0 18px}}</style>