<template><main class="model-page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak Multiplex 6200 Specifications</h1><p>Historical Mazak Multiplex 6200 twin-spindle production turning center specifications organized by year and configuration from UMS machinery records.</p></div></section><section class="wrap section"><div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> Specifications may vary by year, control, automation package and optional equipment.</div><h2>Historical Multiplex 6200 Specifications by Year</h2><SpecYearConfigurations model="Mazak Multiplex 6200" :configurations="configurations" /></section></main></template>
<script setup>
const configurations=[
{year:'1999',title:'1999 Mazak Multiplex 6200',control:'Mazatrol Fusion 640MT',specs:[{label:'Maximum cutting diameter',value:'10.2 in'},{label:'Spindle bore',value:'2.4 in'},{label:'Turrets',value:'Two 12-position turrets'},{label:'Automation',value:'GL100C robot'}]},
{year:'2000',title:'2000 Mazak Multiplex 6200 — Fusion 640T',control:'Mazatrol Fusion 640T',specs:[{label:'Spindles',value:'Twin spindle'},{label:'Chucks',value:'Two 8 in 3-jaw chucks'},{label:'X-axis travel',value:'9.06 in'},{label:'Z-axis travel',value:'17.25 in left / 19.37 in right'},{label:'Maximum spindle speed',value:'3,500 RPM on recorded machine'},{label:'Main motor',value:'30 HP'},{label:'Automation',value:'GL100C gantry robot'}]},
{year:'2000',title:'2000 Mazak Multiplex 6200 — Fusion 640MT',control:'Mazatrol Fusion 640MT / CRT',specs:[{label:'Standard cutting diameter',value:'10.24 in'},{label:'Distance between spindles',value:'46.85 in'},{label:'X-axis travel',value:'9.06 in'},{label:'Z-axis travel',value:'19.37 in recorded'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Equipment',value:'Live tooling and robot loader'}],note:'Multiple 2000 UMS records support the Fusion 640MT production configuration.'}
]
useSeoMeta({title:'Mazak Multiplex 6200 Specifications by Year | UMS Spec Library',description:'Historical Mazak Multiplex 6200 twin-spindle turning center specifications organized by year, control and automation configuration from UMS machinery records.'});useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/multiplex-6200'}]})
</script>
<style scoped>.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.hero p{max-width:820px;line-height:1.7}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;border-radius:6px;margin-bottom:34px}.section h2{color:#0b2545;margin:34px 0 12px}@media(max-width:760px){.wrap{padding:0 18px}}</style>