<template><main class="model-page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak QT-25L Specifications</h1><p>Historical QT-25L specifications organized by year, control and configuration from UMS machinery records.</p></div></section><section class="wrap section"><div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> Specifications may vary by individual machine, year and equipment.</div><h2>Historical QT-25L Specifications by Year</h2><p>UMS records from 1995 through 1998 show a consistent long-bed QT-25L platform with Mazatrol T-PLUS controls, while turret and chuck details vary by machine.</p><SpecYearConfigurations model="Mazak QT-25L" :configurations="configurations" /></section></main></template>
<script setup>
const configurations=[
{year:'1995',title:'1995 Mazak QT-25L',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'20.8 in'},{label:'Swing over cross slide',value:'15.75 in'},{label:'Distance between centers',value:'48.03 in'},{label:'Spindle bore',value:'3.15 in'},{label:'X-axis travel',value:'7.87 in'},{label:'Z-axis travel',value:'48.43 in'},{label:'Maximum spindle speed',value:'3,600 RPM'},{label:'Main motor',value:'25 HP'},{label:'Turret / ATC',value:'12 positions'},{label:'Tailstock taper',value:'#4 MT'},{label:'Chuck diameter',value:'10 in hydraulic'}]},
{year:'1996',title:'1996 Mazak QT-25L — 16-Position Turret',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'20 in'},{label:'Distance between centers',value:'48 in'},{label:'Spindle bore',value:'3.15 in'},{label:'Maximum spindle speed',value:'3,600 RPM'},{label:'Main motor',value:'25 HP'},{label:'Turret',value:'16 positions'},{label:'Chuck diameter',value:'10 in'}]},
{year:'1996',title:'1996 Mazak QT-25L — 12-Position Turret',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'20.8 in'},{label:'Swing over cross slide',value:'15.75 in'},{label:'Distance between centers',value:'48.03 in'},{label:'Spindle bore',value:'3.15 in'},{label:'X-axis travel',value:'7.87 in'},{label:'Z-axis travel',value:'48.43 in'},{label:'Maximum spindle speed',value:'3,600 RPM'},{label:'Main motor',value:'25 HP'},{label:'Turret / ATC',value:'12 positions'},{label:'Tailstock taper',value:'#4 MT'},{label:'Chuck diameter',value:'12 in'}],note:'The UMS database contains two materially different 1996 turret/chuck configurations, so they are kept separate.'},
{year:'1997',title:'1997 Mazak QT-25L',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'20 in'},{label:'Distance between centers',value:'48 in'},{label:'Spindle bore',value:'3.15 in'},{label:'Maximum spindle speed',value:'3,600 RPM'},{label:'Turret',value:'16 positions'},{label:'Chuck diameter',value:'12 in'},{label:'Equipment',value:'Chip conveyor'}]},
{year:'1998',title:'1998 Mazak QT-25L',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'20 in'},{label:'Distance between centers',value:'48 in'},{label:'Spindle bore',value:'3.1 in'},{label:'Maximum spindle speed',value:'3,600 RPM'},{label:'Main motor',value:'25 HP'},{label:'Turret',value:'16 positions'},{label:'Chuck diameter',value:'10 in'}]}]
useSeoMeta({title:'Mazak QT-25L Specifications by Year | UMS Spec Library',description:'Historical Mazak QT-25L CNC lathe specifications organized by year, control and configuration from UMS machinery records.'});useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/qt-25l'}]})
</script>
<style scoped>.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.hero p{max-width:820px;line-height:1.7}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;border-radius:6px;margin-bottom:34px}.section h2{color:#0b2545;margin:34px 0 12px}.section>p{line-height:1.7;max-width:920px}@media(max-width:760px){.wrap{padding:0 18px}}</style>