<template>
  <main class="model-page">
    <section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak QT-20 Specifications</h1><p>Historical specification information for Mazak QT-20 CNC lathes represented in the UMS machinery database.</p></div></section>
    <section class="wrap section">
      <div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> Specifications can vary by year, control, configuration and optional equipment.</div>
      <h2>QT-20 Historical Specification Profile</h2>
      <p>UMS historical QT-20 records from the mid-to-late 1990s consistently show Mazatrol T-PLUS controls and a compact 2-axis CNC turning-center configuration. One detailed historical record provides the specification set below; other QT-20 records show small differences in turret configuration and entered values.</p>
      <div class="spec-grid"><div v-for="s in specs" :key="s.label" class="spec"><span>{{ s.label }}</span><strong>{{ s.value }}</strong></div></div>
      <h2>Variations Seen in UMS Historical Records</h2>
      <div class="variation-grid"><article><h3>Years represented</h3><p>Historical QT-20 records reviewed include 1995, 1996, 1997 and 1998 machines.</p></article><article><h3>Controls</h3><p>Mazatrol T-PLUS / CRT appears consistently in the reviewed QT-20 records.</p></article><article><h3>Turret capacity</h3><p>Historical records show both 8-position and 12-position turret entries.</p></article><article><h3>Common equipment</h3><p>Some records include an 8-inch chuck and chip conveyor; equipment should always be verified on the individual machine.</p></article></div>
      <div class="naming"><h2>QT-20 vs. Quick-Turn 20</h2><p>UMS preserves <strong>QT-20</strong> and <strong>Quick-Turn 20</strong> as separate historical model designations. The database shows materially different specifications and generations under those names, so this page does not automatically combine them.</p><NuxtLink to="/spec-library/mazak/quick-turn-20">See the separate Quick-Turn 20 specification page →</NuxtLink></div>
    </section>
  </main>
</template>
<script setup>
const specs=[{label:'Swing',value:'17.32 in.'},{label:'Maximum Machining Diameter',value:'11.81 in.'},{label:'Distance Between Centers',value:'17.5 in.'},{label:'Spindle Speed',value:'50–5,000 RPM'},{label:'Spindle Bore',value:'2.44 in.'},{label:'Main Motor',value:'20 HP'},{label:'Spindle Nose',value:'A2-6'},{label:'Turret',value:'12 positions (detailed record)'},{label:'X-Axis Travel',value:'7.125 in.'},{label:'Z-Axis Travel',value:'20.125 in.'},{label:'Chuck Diameter',value:'8 in.'},{label:'Tailstock Body Travel',value:'18.11 in.'}]
useSeoMeta({title:'Mazak QT-20 Specifications | CNC Lathe Specs | UMS',description:'Mazak QT-20 CNC lathe specifications from historical UMS machinery records, including swing, turning diameter, spindle bore, RPM, horsepower, travels and turret information.',ogTitle:'Mazak QT-20 Specifications | UMS Spec Library',ogDescription:'Historical Mazak QT-20 CNC lathe specifications and configuration information.',ogType:'article',ogUrl:'https://usedmachinerysource.com/spec-library/mazak/qt-20'})
useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/qt-20'}]})
</script>
<style scoped>.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:auto;padding-left:28px;padding-right:28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-weight:900;letter-spacing:.12em;font-size:.78rem;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.section{padding-top:42px}.warning{border-left:5px solid #c55a11;background:#fff5eb;padding:18px 20px;margin-bottom:36px}.section h2{margin-top:36px}.section>p{line-height:1.75}.spec-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:24px 0}.spec{border:1px solid #d9e1e8;border-radius:9px;padding:16px;background:#f7f9fb}.spec span{display:block;color:#5d6d7e;font-size:.86rem;margin-bottom:5px}.variation-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.variation-grid article,.naming{border:1px solid #d9e1e8;border-radius:10px;padding:20px}.variation-grid h3{margin-top:0}.naming{margin-top:36px;background:#f4f7fa}.naming h2{margin-top:0}.naming a{color:#1c4587;font-weight:800;text-decoration:none}@media(max-width:760px){.spec-grid,.variation-grid{grid-template-columns:1fr}.wrap{padding-left:18px;padding-right:18px}}</style>