<template>
  <main class="model-page">
    <section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak QT-20 Specifications</h1><p>Historical Mazak QT-20 specifications organized by year and configuration from machines represented in the UMS database.</p></div></section>
    <section class="wrap section">
      <div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> These values come from individual UMS machinery records. Specifications can vary by year, control, configuration and optional equipment.</div>
      <h2>Historical QT-20 Specifications by Year</h2>
      <p>Choose the year/configuration closest to the machine you are researching. Records with materially different turret or machine configurations are kept separate instead of being blended into one generic specification.</p>
      <article v-for="c in configurations" :key="c.title" class="configuration">
        <div class="config-head"><div><div class="year">{{ c.year }}</div><h3>{{ c.title }}</h3><p><strong>Control:</strong> {{ c.control }}</p></div><button type="button" class="copy" @click="copySpecs(c)">{{ copied===c.title ? 'Copied!' : 'Copy Specifications' }}</button></div>
        <div class="spec-grid"><div v-for="s in c.specs" :key="s.label" class="spec"><span>{{s.label}}</span><strong>{{s.value}}</strong></div></div>
        <p v-if="c.note" class="note">{{c.note}}</p>
      </article>
      <div class="naming"><h2>QT-20 vs. Quick-Turn 20</h2><p>UMS preserves <strong>QT-20</strong> and <strong>Quick-Turn 20</strong> as separate historical model designations. The database shows materially different specifications and generations under those names, so this page does not automatically combine them.</p><NuxtLink to="/spec-library/mazak/quick-turn-20">See the separate Quick-Turn 20 specification page →</NuxtLink></div>
      <div class="related"><h2>More Mazak turning specifications</h2><div class="related-links"><NuxtLink to="/spec-library/mazak/quick-turn-10">Quick-Turn 10</NuxtLink><NuxtLink to="/spec-library/mazak/quick-turn-18n">Quick-Turn 18N</NuxtLink><NuxtLink to="/spec-library/mazak/quick-turn-20">Quick-Turn 20</NuxtLink></div></div>
    </section>
  </main>
</template>
<script setup>
import { ref } from 'vue'
const copied=ref('')
const configurations=[
 {year:'1995',title:'1995 Mazak QT-20 — 12-Position Turret',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'17.3 in'},{label:'Distance between centers',value:'20 in'},{label:'Spindle bore',value:'2.4 in'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Main motor',value:'20 HP on recorded machine'},{label:'Turret',value:'12 positions'}],note:'Two 1995 QT-20 records in the UMS database show this same general configuration.'},
 {year:'1996',title:'1996 Mazak QT-20 — 8-Position Turret',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'17.3 in'},{label:'Distance between centers',value:'20 in'},{label:'Spindle bore',value:'2.44 in'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Turret',value:'8 positions'},{label:'Chuck diameter',value:'8 in'}],note:'UMS has multiple 1996 records showing this configuration.'},
 {year:'1997',title:'1997 Mazak QT-20 — 12-Position Turret',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'17.3 in'},{label:'Distance between centers',value:'20 in'},{label:'Spindle bore',value:'2.4 in'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Turret',value:'12 positions'},{label:'Main motor',value:'20 HP on recorded 12-position machine'}],note:'A separate 1997 QT-20 chucker record has an 8-position turret, 8-inch chuck and chip conveyor.'},
 {year:'1997',title:'1997 Mazak QT-20 — Chucker / 8-Position Turret',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'17.3 in'},{label:'Spindle bore',value:'2.4 in'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Turret',value:'8 positions'},{label:'Chuck diameter',value:'8 in'},{label:'Equipment',value:'Chip conveyor'}]},
 {year:'1998',title:'1998 Mazak QT-20',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'17 in'},{label:'Distance between centers',value:'20 in'},{label:'Spindle bore',value:'2.4 in'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Main motor',value:'20 HP'},{label:'Turret',value:'8 positions'},{label:'Chuck diameter',value:'8 in'}]}
]
function copySpecs(c){const text=[`Mazak QT-20 - ${c.year}`,`Control: ${c.control}`,...c.specs.map(s=>`${s.label}: ${s.value}`)].join('\n');navigator.clipboard.writeText(text);copied.value=c.title;setTimeout(()=>{if(copied.value===c.title)copied.value=''},1800)}
useSeoMeta({title:'Mazak QT-20 Specifications by Year | UMS Spec Library',description:'Historical Mazak QT-20 CNC lathe specifications organized by year, control and configuration from UMS machinery records.'})
useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/qt-20'}]})
</script>
<style scoped>
.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.hero p{max-width:820px;line-height:1.7}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;border-radius:6px;margin-bottom:34px}.section h2{color:#0b2545;margin:34px 0 12px}.section>p{line-height:1.7;max-width:920px}.configuration{border:1px solid #cfd9e3;border-radius:10px;padding:24px;margin:24px 0;background:#fff}.config-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.config-head h3{font-size:1.35rem;color:#0b2545;margin:4px 0 6px}.config-head p{margin:0}.year{font-size:.78rem;font-weight:900;letter-spacing:.1em;color:#1c4587}.copy{border:0;border-radius:6px;background:#1c4587;color:#fff;font-weight:800;padding:11px 16px;cursor:pointer;white-space:nowrap}.spec-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:20px}.spec{border:1px solid #d7e0e8;border-radius:8px;padding:15px;background:#f8fafc}.spec span{display:block;color:#657688;font-size:.76rem;text-transform:uppercase;font-weight:800;margin-bottom:6px}.spec strong{color:#0b2545}.note{color:#53677a;line-height:1.55;margin-bottom:0}.naming,.related{margin-top:40px;padding:24px;background:#f3f6f9;border-radius:10px}.naming h2,.related h2{margin-top:0}.naming p{line-height:1.65}.naming a,.related a{color:#1c4587;font-weight:800;text-decoration:none}.related-links{display:flex;flex-wrap:wrap;gap:14px}@media(max-width:760px){.spec-grid{grid-template-columns:1fr}.config-head{display:block}.copy{margin-top:14px}.wrap{padding:0 18px}}
</style>