<template>
  <main class="model-page">
    <section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak QT-20 Specifications</h1><p>Historical specification information for Mazak QT-20 CNC lathes represented in the UMS machinery database.</p></div></section>
    <section class="wrap section">
      <div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> Specifications can vary by year, control, configuration and optional equipment.</div>
      <h2>QT-20 Historical Specification Profile</h2>
      <p>UMS historical QT-20 records from the mid-to-late 1990s consistently show Mazatrol T-PLUS controls and a compact 2-axis CNC turning-center configuration. One detailed historical record provides the specification set below; other QT-20 records show small differences in turret configuration and entered values.</p>
      <div class="spec-grid"><div v-for="s in specs" :key="s.label" class="spec"><span>{{ s.label }}</span><strong>{{ s.value }}</strong></div></div>
      <h2>Variations Seen in UMS Historical Records</h2>
      <div class="variation-grid"><article><h3>Years represented</h3><p>Historical QT-20 records reviewed include 1995, 1996, 1997 and 1998 machines.</p></article><article><h3>Controls</h3><p>Mazatrol T-PLUS / CRT appears consistently in the reviewed QT-20 records.</p></article><article><h3>Turret capacity</h3><p>Historical records show both 8-position and 12-position turret entries.</p></article><article><h3>Common equipment</h3><p>Some records include an 8-inch chuck and chip conveyor; equipment should always be verified on the individual machine.</p></article></div>
      <div class="naming"><h2>QT-20 vs. Quick-Turn 20</h2><p>UMS preserves <strong>QT-20</strong> and <strong>Quick-Turn 20</strong> as separate historical model designations. The database shows materially different specifications and generations under those names, so this page does not automatically combine them.</p><NuxtLink to="/spec-library/mazak/quick-turn-20">See the separate Quick-Turn 20 specification page →</NuxtLink></div>
      <div class="related"><h2>More Mazak turning specifications</h2><div class="related-links"><NuxtLink to="/spec-library/mazak/quick-turn-10">Quick-Turn 10</NuxtLink><NuxtLink to="/spec-library/mazak/quick-turn-18n">Quick-Turn 18N</NuxtLink><NuxtLink to="/spec-library/mazak/quick-turn-20">Quick-Turn 20</NuxtLink></div></div>
    </section>
  </main>
</template>
<script setup>
const specs=[{label:'Swing',value:'17.32 in'},{label:'Maximum machining diameter',value:'11.81 in'},{label:'Distance between centers',value:'17.5 in'},{label:'Spindle speed',value:'50–5,000 RPM'},{label:'Spindle bore',value:'2.44 in'},{label:'Main motor',value:'20 HP'},{label:'Spindle nose',value:'A2-6'},{label:'Turret',value:'12 positions on detailed record'},{label:'X-axis travel',value:'7.125 in'},{label:'Z-axis travel',value:'20.125 in'},{label:'Chuck diameter',value:'8 in'}]
useSeoMeta({title:'Mazak QT-20 Specifications | UMS Spec Library',description:'Historical Mazak QT-20 CNC lathe specifications including swing, machining diameter, spindle bore, speed, horsepower, travel and turret capacity.'})
useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/qt-20'}]})
</script>
<style scoped>
.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.hero p{max-width:820px;line-height:1.7}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;border-radius:6px;margin-bottom:34px}.section h2{color:#0b2545;margin:34px 0 12px}.section>p{line-height:1.7;max-width:920px}.spec-grid,.variation-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:20px}.spec,.variation-grid article{border:1px solid #d7e0e8;border-radius:8px;padding:17px;background:#f8fafc}.spec span{display:block;color:#657688;font-size:.78rem;text-transform:uppercase;font-weight:800;margin-bottom:6px}.spec strong{color:#0b2545;font-size:1.05rem}.variation-grid h3{margin-top:0;color:#0b2545}.variation-grid p{line-height:1.55}.naming,.related{margin-top:40px;padding:24px;background:#f3f6f9;border-radius:10px}.naming h2,.related h2{margin-top:0}.naming p{line-height:1.65}.naming a,.related a{color:#1c4587;font-weight:800;text-decoration:none}.related-links{display:flex;flex-wrap:wrap;gap:14px}@media(max-width:760px){.spec-grid,.variation-grid{grid-template-columns:1fr}.wrap{padding:0 18px}}
</style>