<template><main class="model-page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak QT-250HP Specifications</h1><p>Historical QT-250HP specifications organized by year and configuration from UMS machinery records.</p></div></section><section class="wrap section"><div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> Specifications may vary by individual machine and equipment.</div><h2>Historical QT-250HP Specifications by Year</h2><p>UMS records from 1999 through 2001 show a consistent Fusion 640-era platform, with some variation in entered swing and equipment.</p><SpecYearConfigurations model="Mazak QT-250HP" :configurations="configurations" /></section></main></template>
<script setup>
const configurations=[
{year:'1999',title:'1999 Mazak QT-250HP',control:'Mazatrol Fusion 640T / CRT',specs:[{label:'Swing',value:'23.6 in'},{label:'Distance between centers',value:'20 in'},{label:'Spindle bore',value:'3.1 in'},{label:'Maximum spindle speed',value:'4,000 RPM'},{label:'Main motor',value:'20 HP'},{label:'Turret',value:'12 positions'},{label:'Chuck diameter',value:'10 in'},{label:'Equipment',value:'Barfeed'}]},
{year:'2000',title:'2000 Mazak QT-250HP',control:'Mazatrol Fusion 640T / CRT',specs:[{label:'Swing',value:'21.65–23.6 in in UMS records'},{label:'Maximum machining diameter',value:'15.7 in on detailed record'},{label:'Distance between centers',value:'19.68 in on detailed record'},{label:'Spindle bore',value:'3.1 in on recorded machine'},{label:'Maximum spindle speed',value:'4,000 RPM'},{label:'Main motor',value:'20 HP on recorded machine'},{label:'Turret',value:'12 positions'},{label:'Chuck diameter',value:'10 in'}],note:'Two 2000 records use different entered swing values, so both are preserved rather than averaged.'},
{year:'2001',title:'2001 Mazak QT-250HP — Universal',control:'Mazatrol Fusion 640T',specs:[{label:'Swing',value:'23.6 in'},{label:'Distance between centers',value:'20 in'},{label:'Spindle bore',value:'3.1–3.15 in in UMS records'},{label:'Maximum spindle speed',value:'4,000 RPM'},{label:'Main motor',value:'20 HP on recorded machine'},{label:'Turret',value:'12 positions'},{label:'Chuck diameter',value:'10 in'},{label:'Equipment',value:'Tool eye; chip conveyor on one record'}]},
{year:'2001',title:'2001 Mazak QT-250HP — Chucker',control:'Mazatrol Fusion 640T-PC / CRT',specs:[{label:'Swing',value:'21.6 in'},{label:'Maximum turning diameter',value:'15.7 in'},{label:'Spindle bore',value:'3.1 in'},{label:'Maximum spindle speed',value:'4,000 RPM'},{label:'Turret',value:'12 positions'},{label:'Chuck diameter',value:'10 in'},{label:'Configuration',value:'CNC chucker'},{label:'Equipment',value:'12 ft bar feed'}]}]
useSeoMeta({title:'Mazak QT-250HP Specifications by Year | UMS Spec Library',description:'Historical Mazak QT-250HP CNC lathe specifications organized by year, control and configuration from UMS machinery records.'});useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/qt-250hp'}]})
</script>
<style scoped>.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.hero p{max-width:820px;line-height:1.7}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;border-radius:6px;margin-bottom:34px}.section h2{color:#0b2545;margin:34px 0 12px}.section>p{line-height:1.7;max-width:920px}@media(max-width:760px){.wrap{padding:0 18px}}</style>