<template>
  <main class="model-page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak Quick-Turn 20 Specifications</h1><p>Historical specification and configuration information for Mazak Quick-Turn 20 CNC lathes represented in the UMS machinery database.</p></div></section>
  <section class="wrap section"><div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> Specifications vary by year, generation, control and equipment.</div>
  <h2>Earlier Quick-Turn 20 Records</h2><p>The UMS database contains Quick-Turn 20 records from the 1980s with Mazatrol T-1 and T-2 controls. These machines are materially different from the later QT-20 records, which is why UMS keeps the model designations separate.</p>
  <div class="spec-grid"><div v-for="s in earlySpecs" :key="s.label" class="spec"><span>{{s.label}}</span><strong>{{s.value}}</strong></div></div>
  <h2>Later Quick-Turn 20 Records</h2><p>The same historical model wording also appears on later 1997–1998 records with Mazatrol T-PLUS controls and substantially different capacities. Rather than presenting one specification set as universal, the library shows the variation by generation.</p>
  <div class="spec-grid"><div v-for="s in laterSpecs" :key="s.label" class="spec"><span>{{s.label}}</span><strong>{{s.value}}</strong></div></div>
  <div class="naming"><h2>Related designation: Mazak QT-20</h2><p>QT-20 is retained separately because the UMS historical data shows a distinct later specification pattern. Keeping both terms visible also reflects the way older machinery is actually entered and searched.</p><NuxtLink to="/spec-library/mazak/qt-20">View Mazak QT-20 specifications →</NuxtLink></div></section></main>
</template>
<script setup>
const earlySpecs=[{label:'Years reviewed',value:'1983–1987'},{label:'Swing',value:'about 20 in'},{label:'Distance between centers',value:'about 38.8–40 in'},{label:'Spindle bore / hole',value:'about 3.1–3.15 in'},{label:'Maximum spindle speed',value:'3,000 RPM'},{label:'Main motor',value:'25 HP'},{label:'Turret',value:'8 positions'}]
const laterSpecs=[{label:'Years reviewed',value:'1997–1998'},{label:'Swing',value:'about 17.3–20.1 in in reviewed records'},{label:'Distance between centers',value:'about 17.5–19.7 in'},{label:'Spindle bore / bar capacity',value:'about 2.0–2.4 in on reviewed records'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Main motor',value:'15–20 HP in reviewed records'},{label:'Turret',value:'8–12 positions'}]
useSeoMeta({title:'Mazak Quick-Turn 20 Specifications | UMS Spec Library',description:'Historical Mazak Quick-Turn 20 CNC lathe specifications showing differences between earlier and later generations in the UMS Machinery Specification Library.'})
useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/quick-turn-20'}]})
</script>
<style scoped>
.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.hero p{max-width:820px;line-height:1.7}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;border-radius:6px;margin-bottom:34px}.section h2{color:#0b2545;margin:34px 0 12px}.section>p{line-height:1.7;max-width:920px}.spec-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:20px}.spec{border:1px solid #d7e0e8;border-radius:8px;padding:17px;background:#f8fafc}.spec span{display:block;color:#657688;font-size:.78rem;text-transform:uppercase;font-weight:800;margin-bottom:6px}.spec strong{color:#0b2545;font-size:1.05rem}.naming{margin-top:40px;padding:24px;background:#f3f6f9;border-radius:10px}.naming h2{margin-top:0}.naming p{line-height:1.65}.naming a{color:#1c4587;font-weight:800;text-decoration:none}@media(max-width:760px){.spec-grid{grid-template-columns:1fr}.wrap{padding:0 18px}}
</style>