<template><main class="model-page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak Quick-Turn 8 Specifications</h1><p>Historical Quick-Turn 8 specifications organized by year, control and configuration from UMS machinery records.</p></div></section><section class="wrap section"><div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> Specifications may vary by individual machine, year and equipment.</div><h2>Historical Quick-Turn 8 Specifications by Year</h2><p>UMS records show changes in control and spindle speed across the Quick-Turn 8 years represented below, so each configuration is shown separately.</p><SpecYearConfigurations model="Mazak Quick-Turn 8" :configurations="configurations" /></section></main></template>
<script setup>
const configurations=[
{year:'1986',title:'1986 Mazak Quick-Turn 8',control:'Mazatrol T2 / CRT',specs:[{label:'Swing',value:'11.8 in'},{label:'Distance between centers',value:'12 in'},{label:'Spindle hole',value:'1.97 in'},{label:'Maximum spindle speed',value:'4,500 RPM'},{label:'Main motor',value:'10 HP'},{label:'Turret',value:'8 positions'}]},
{year:'1988',title:'1988 Mazak Quick-Turn 8',control:'Mazatrol T2 / CRT',specs:[{label:'Swing',value:'11.8 in'},{label:'Distance between centers',value:'11.2–12 in in UMS records'},{label:'Spindle bore / hole',value:'1.97 in'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Main motor',value:'10 HP on recorded machine'},{label:'Turret',value:'8 positions'}],note:'Multiple 1988 records support this general configuration.'},
{year:'1991',title:'1991 Mazak Quick-Turn 8',control:'Mazatrol T32-2 / CRT',specs:[{label:'Swing',value:'11.8 in'},{label:'Distance between centers',value:'11–12 in in UMS records'},{label:'Spindle hole',value:'1.97 in'},{label:'Maximum spindle speed',value:'4,500–6,000 RPM in UMS records'},{label:'Main motor',value:'10 HP on recorded machine'},{label:'Turret',value:'8 positions'}]},
{year:'1993',title:'1993 Mazak Quick-Turn 8',control:'Mazatrol T32-2 / CRT',specs:[{label:'Swing',value:'11.8 in'},{label:'Distance between centers',value:'10 in on universal record'},{label:'Spindle bore / hole',value:'1.96 in'},{label:'Maximum spindle speed',value:'5,000–6,000 RPM in UMS records'},{label:'Turret',value:'8 positions'},{label:'Configuration',value:'Universal and chucker records'}]},
{year:'1994',title:'1994 Mazak Quick-Turn 8',control:'Mazatrol T-32B / CRT',specs:[{label:'Swing',value:'11.8 in'},{label:'Distance between centers',value:'12 in'},{label:'Spindle hole',value:'1.97 in'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Main motor',value:'10 HP'},{label:'Turret',value:'8 positions'}]}]
useSeoMeta({title:'Mazak Quick-Turn 8 Specifications by Year | UMS Spec Library',description:'Historical Mazak Quick-Turn 8 CNC lathe specifications organized by year, control and configuration from UMS machinery records.'});useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/quick-turn-8'}]})
</script>
<style scoped>.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.hero p{max-width:820px;line-height:1.7}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;border-radius:6px;margin-bottom:34px}.section h2{color:#0b2545;margin:34px 0 12px}.section>p{line-height:1.7;max-width:920px}@media(max-width:760px){.wrap{padding:0 18px}}</style>