<template>
  <main class="model-page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak Quick-Turn 20 Specifications</h1><p>Historical specification and configuration information for Mazak Quick-Turn 20 CNC lathes represented in the UMS machinery database.</p></div></section>
  <section class="wrap section"><div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> Specifications vary by year, generation, control and equipment.</div>
  <h2>Earlier Quick-Turn 20 Records</h2><p>The UMS database contains Quick-Turn 20 records from the 1980s with Mazatrol T-1 and T-2 controls. These machines are materially different from the later QT-20 records, which is why UMS keeps the model designations separate.</p>
  <div class="spec-grid"><div v-for="s in earlySpecs" :key="s.label" class="spec"><span>{{s.label}}</span><strong>{{s.value}}</strong></div></div>
  <h2>Later Quick-Turn 20 Records</h2><p>The same historical model wording also appears on later 1997–1998 records with Mazatrol T-PLUS controls and substantially different capacities. Rather than presenting one specification set as universal, the library shows the variation by generation.</p>
  <div class="spec-grid"><div v-for="s in laterSpecs" :key="s.label" class="spec"><span>{{s.label}}</span><strong>{{s.value}}</strong></div></div>
  <div class="naming"><h2>Related designation: Mazak QT-20</h2><p>QT-20 is retained separately because the UMS historical data shows a distinct later specification pattern. Keeping both terms visible also reflects the way older machinery is actually entered and searched.</p><NuxtLink to="/spec-library/mazak/qt-20">View Mazak QT-20 specifications →</NuxtLink></div></section></main>
</template>
<script setup>
const earlySpecs=[{label:'Years represented in reviewed records',value:'1983–1987'},{label:'Swing',value:'about 20 in.'},{label:'Distance Between Centers',value:'about 38.8–40 in.'},{label:'Spindle Bore',value:'about 3.1–3.15 in.'},{label:'Spindle Speed',value:'3,000 RPM'},{label:'Main Motor',value:'25 HP'},{label:'Turret',value:'8 positions'},{label:'Typical Chuck Entry',value:'10 in.'},{label:'Controls seen',value:'Mazatrol T-1 / T-2; one Fanuc 10T record'}]
const laterSpecs=[{label:'Years represented in reviewed records',value:'1997–1998'},{label:'Swing',value:'about 17.3–20.1 in. in entered records'},{label:'Machining / center length',value:'about 17.5–20 in. in entered records'},{label:'Spindle Bore / Bar Capacity',value:'about 2.0–2.4 in. entries'},{label:'Spindle Speed',value:'5,000 RPM'},{label:'Main Motor',value:'15–20 HP entries'},{label:'Chuck',value:'8 in. entries'},{label:'Turret',value:'8–12 tools in entered records'},{label:'Control',value:'Mazatrol T-PLUS'}]
useSeoMeta({title:'Mazak Quick-Turn 20 Specifications | UMS Spec Library',description:'Historical Mazak Quick-Turn 20 CNC lathe specifications from UMS records, including 1980s and later T-PLUS generation capacity and control information.',ogTitle:'Mazak Quick-Turn 20 Specifications | UMS',ogDescription:'Historical Mazak Quick-Turn 20 CNC lathe specifications and generation differences.',ogType:'article',ogUrl:'https://usedmachinerysource.com/spec-library/mazak/quick-turn-20'})
useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/quick-turn-20'}]})
</script>
<style scoped>.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:auto;padding-left:28px;padding-right:28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-weight:900;letter-spacing:.12em;font-size:.78rem;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.section{padding-top:42px}.warning{border-left:5px solid #c55a11;background:#fff5eb;padding:18px 20px;margin-bottom:36px}.section h2{margin-top:38px}.section>p{line-height:1.75}.spec-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:24px 0}.spec{border:1px solid #d9e1e8;border-radius:9px;padding:16px;background:#f7f9fb}.spec span{display:block;color:#5d6d7e;font-size:.86rem;margin-bottom:5px}.naming{margin-top:40px;border:1px solid #d9e1e8;border-radius:10px;padding:22px;background:#f4f7fa}.naming h2{margin-top:0}.naming a{color:#1c4587;font-weight:800;text-decoration:none}@media(max-width:760px){.spec-grid{grid-template-columns:1fr}.wrap{padding-left:18px;padding-right:18px}}</style>