<template><main class="model-page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak Quick-Turn 8N Specifications</h1><p>Historical Quick-Turn 8N specifications organized by year, control and configuration from UMS machinery records.</p></div></section><section class="wrap section"><div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> Specifications may vary by individual machine, year and equipment.</div><h2>Historical Quick-Turn 8N Specifications by Year</h2><p>UMS records show meaningful turret and spindle-speed variation even within the same year, so separate configurations are retained when needed.</p><SpecYearConfigurations model="Mazak Quick-Turn 8N" :configurations="configurations" /></section></main></template>
<script setup>
const configurations=[
{year:'1989',title:'1989 Mazak Quick-Turn 8N — 8-Position Turret',control:'Mazatrol T32-2 / CRT',specs:[{label:'Swing',value:'11.8 in'},{label:'Distance between centers',value:'12 in'},{label:'Spindle bore',value:'1.97 in'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Turret',value:'8 positions'}]},
{year:'1989',title:'1989 Mazak Quick-Turn 8N — 12-Position Turret',control:'Mazatrol T32-2 / CRT',specs:[{label:'Swing',value:'11.8 in'},{label:'Distance between centers',value:'12 in'},{label:'Spindle hole',value:'1.97 in'},{label:'Maximum spindle speed',value:'6,000 RPM'},{label:'Turret',value:'12 positions'},{label:'Equipment',value:'Parts catcher; chip conveyor'}],note:'This second 1989 record is kept separate because its turret capacity and spindle speed differ materially.'},
{year:'1990',title:'1990 Mazak Quick-Turn 8N',control:'Mazatrol T-32 / CRT',specs:[{label:'Recorded detailed specs',value:'Not available in UMS machine summary'},{label:'Control',value:'Mazatrol T-32 / CRT'}],note:'UMS has a 1990 machine record, but the summary does not contain enough detailed capacities to infer a specification set.'},
{year:'1993',title:'1993 Mazak Quick-Turn 8N — Universal',control:'Mazatrol T32B / CRT',specs:[{label:'Swing',value:'11.8 in'},{label:'Distance between centers',value:'10 in'},{label:'Spindle hole',value:'1.96 in'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Main motor',value:'10 HP'},{label:'Turret',value:'8 positions'}]},
{year:'1993',title:'1993 Mazak Quick-Turn 8N — Chucker',control:'Mazatrol T32-2 / CRT',specs:[{label:'Swing',value:'11.8 in'},{label:'Spindle bore',value:'1.96 in'},{label:'Maximum spindle speed',value:'5,000 RPM'},{label:'Main motor',value:'10 HP'},{label:'Turret',value:'8 positions'},{label:'Configuration',value:'CNC chucker'},{label:'Equipment',value:'Tool eye; chip conveyor'}]}]
useSeoMeta({title:'Mazak Quick-Turn 8N Specifications by Year | UMS Spec Library',description:'Historical Mazak Quick-Turn 8N CNC lathe specifications organized by year, control and configuration from UMS machinery records.'});useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/quick-turn-8n'}]})
</script>
<style scoped>.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.hero p{max-width:820px;line-height:1.7}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;border-radius:6px;margin-bottom:34px}.section h2{color:#0b2545;margin:34px 0 12px}.section>p{line-height:1.7;max-width:920px}@media(max-width:760px){.wrap{padding:0 18px}}</style>