<template><main class="model-page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak Slant-Turn 50 Specifications</h1><p>Historical Slant-Turn 50 specifications organized by year, control and configuration from UMS machinery records.</p></div></section><section class="wrap section"><div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> Specifications may vary by individual machine, year, bed length, bore size and equipment.</div><h2>Historical Slant-Turn 50 Specifications by Year</h2><p>UMS records show substantial changes in controls, bed length, spindle bore and turret configuration across the Slant-Turn 50 years represented below.</p><SpecYearConfigurations model="Mazak Slant-Turn 50" :configurations="configurations" /></section></main></template>
<script setup>
const configurations=[
{year:'1983',title:'1983 Mazak Slant-Turn 50',control:'Mazatrol T1 / CRT',specs:[{label:'Swing',value:'30 in'},{label:'Swing over carriage',value:'22 in'},{label:'Distance between centers',value:'60 in'},{label:'Spindle bore',value:'4 in'},{label:'Maximum spindle speed',value:'1,600 RPM'},{label:'Turret',value:'15 positions'}]},
{year:'1984',title:'1984 Mazak Slant-Turn 50',control:'Mazatrol T1 / CRT',specs:[{label:'Swing',value:'30 in'},{label:'Distance between centers',value:'60 in'},{label:'Spindle hole',value:'6.5 in'},{label:'Maximum spindle speed',value:'1,600 RPM'},{label:'Main motor',value:'50 HP'},{label:'Turret',value:'15 positions'}]},
{year:'1985',title:'1985 Mazak Slant-Turn 50',control:'Mazatrol T2 / CRT',specs:[{label:'Swing',value:'31 in'},{label:'Distance between centers',value:'60 in'},{label:'Spindle bore',value:'4 in'},{label:'Maximum spindle speed',value:'1,600 RPM'},{label:'Main motor',value:'50 HP'},{label:'Turret',value:'12 positions'}]},
{year:'1988',title:'1988 Mazak Slant-Turn 50 — Long Bed',control:'Mazatrol T-2 / CRT',specs:[{label:'Swing',value:'31.7 in'},{label:'Distance between centers',value:'120 in'},{label:'Spindle hole',value:'4 in'},{label:'Maximum spindle speed',value:'1,800 RPM'},{label:'Main motor',value:'50 HP'},{label:'Turret',value:'12 positions'},{label:'Chuck diameter',value:'21 in hydraulic'}]},
{year:'1990',title:'1990 Mazak Slant-Turn 50',control:'Mazatrol T32-2 / CRT',specs:[{label:'Swing',value:'31.7 in'},{label:'Distance between centers',value:'60 in'},{label:'Spindle bore',value:'4.1 in'},{label:'Maximum spindle speed',value:'1,600 RPM'},{label:'Main motor',value:'50 HP'},{label:'Turret',value:'15 positions'},{label:'Chuck diameter',value:'24 in hydraulic'}]},
{year:'1997',title:'1997 Mazak Slant-Turn 50 — Large Bore',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'31.7 in'},{label:'Distance between centers',value:'80 in'},{label:'Spindle hole',value:'7 in'},{label:'Maximum spindle speed',value:'1,000 RPM'},{label:'Main motor',value:'50 HP'},{label:'Turret',value:'15 positions'},{label:'Chuck diameter',value:'20 in SMW'},{label:'Equipment',value:'Chip conveyor; EIA'}]},
{year:'1998',title:'1998 Mazak Slant-Turn 50 — Long Bed',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'31.7 in'},{label:'Distance between centers',value:'120 in'},{label:'Spindle hole',value:'4 in'},{label:'Maximum spindle speed',value:'1,600 RPM'},{label:'Main motor',value:'50 HP'},{label:'Turret',value:'15 positions'},{label:'Chuck diameter',value:'24 in hydraulic'}]}]
useSeoMeta({title:'Mazak Slant-Turn 50 Specifications by Year | UMS Spec Library',description:'Historical Mazak Slant-Turn 50 CNC lathe specifications organized by year, control, bore size and configuration from UMS machinery records.'});useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/slant-turn-50'}]})
</script>
<style scoped>.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.hero p{max-width:820px;line-height:1.7}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;border-radius:6px;margin-bottom:34px}.section h2{color:#0b2545;margin:34px 0 12px}.section>p{line-height:1.7;max-width:920px}@media(max-width:760px){.wrap{padding:0 18px}}</style>