<template><main class="model-page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak SQT-250M Specifications</h1><p>Historical Mazak SQT-250M live-tool turning center specifications organized by year and control from UMS machinery records.</p></div></section><section class="wrap section"><div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> Specifications may vary by year, control, configuration and optional equipment.</div><h2>Historical SQT-250M Specifications by Year</h2><SpecYearConfigurations model="Mazak SQT-250M" :configurations="configurations" /></section></main></template>
<script setup>
const configurations=[
{year:'1996',title:'1996 Mazak SQT-250M',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Swing',value:'20.6 in'},{label:'Distance between centers',value:'19.6 in'},{label:'Spindle bore',value:'2.99 in'},{label:'Maximum spindle speed',value:'4,000 RPM'},{label:'Main motor',value:'25 HP'},{label:'Turret',value:'12 positions'},{label:'Chuck',value:'10 in'},{label:'Equipment',value:'Parts catcher'}]},
{year:'2000',title:'2000 Mazak SQT-250M — Fusion 640MT',control:'Mazatrol Fusion 640MT',specs:[{label:'Swing',value:'20.6 in'},{label:'Distance between centers',value:'20 in'},{label:'Spindle bore',value:'2.99 in'},{label:'Turret',value:'12 positions'},{label:'Chuck',value:'10 in'},{label:'Equipment',value:'Live tooling'}],note:'A second 2000 UMS record lists 11.81 in maximum turning diameter, 20.67 in maximum turning length, 25 HP and 4,000 RPM.'},
{year:'2002',title:'2002 Mazak SQT-250M',control:'Mazatrol Fusion 640T / CRT',specs:[{label:'Swing',value:'20.6 in'},{label:'Distance between centers',value:'19.6 in'},{label:'Spindle bore',value:'3 in'},{label:'Maximum spindle speed',value:'4,000 RPM'},{label:'Turret',value:'12 positions'},{label:'Chuck',value:'10 in'}]}
]
useSeoMeta({title:'Mazak SQT-250M Specifications by Year | UMS Spec Library',description:'Historical Mazak SQT-250M specifications organized by year, control and configuration from UMS machinery records.'});useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/sqt-250m'}]})
</script>
<style scoped>.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.hero p{max-width:820px;line-height:1.7}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;border-radius:6px;margin-bottom:34px}.section h2{color:#0b2545;margin:34px 0 12px}@media(max-width:760px){.wrap{padding:0 18px}}</style>