<template><main class="model-page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/mazak/cnc-lathes" class="back">← Mazak CNC Lathe Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Mazak SQT-250MS Specifications</h1><p>Historical Mazak SQT-250MS live-tool, sub-spindle turning center specifications organized by year and control from UMS machinery records.</p></div></section><section class="wrap section"><div class="warning"><strong>Historical specification information — not a machine-for-sale listing.</strong> Specifications may vary by year, control, configuration and optional equipment.</div><h2>Historical SQT-250MS Specifications by Year</h2><SpecYearConfigurations model="Mazak SQT-250MS" :configurations="configurations" /></section></main></template>
<script setup>
const configurations=[
{year:'1998',title:'1998 Mazak SQT-250MS',control:'Mazatrol T-PLUS / CRT',specs:[{label:'Maximum machining diameter',value:'11.81 in'},{label:'Swing',value:'20.67 in'},{label:'X-axis travel',value:'7.5 in'},{label:'Z-axis travel',value:'22.625 in'},{label:'B-axis / between spindles',value:'23 in recorded'},{label:'Equipment',value:'Live tooling and sub-spindle'}]},
{year:'1999',title:'1999 Mazak SQT-250MS',control:'Mazatrol Fusion 640MT',specs:[{label:'Swing',value:'20.6–20.7 in'},{label:'Maximum turning diameter',value:'11.81 in on detailed record'},{label:'Spindle bore',value:'2.99 in'},{label:'Maximum spindle speed',value:'4,000 RPM'},{label:'Turret',value:'12 positions'},{label:'X-axis travel',value:'7.5 in on detailed record'},{label:'Z-axis travel',value:'22.625 in on detailed record'},{label:'Equipment',value:'Live tooling, sub-spindle, C-axis'}],note:'Two 1999 UMS records support this general configuration.'},
{year:'2000',title:'2000 Mazak SQT-250MS',control:'Mazatrol Fusion 640MT',specs:[{label:'Swing',value:'20.6 in'},{label:'Spindle bore',value:'3 in'},{label:'Turret',value:'12 positions'},{label:'Chuck',value:'10 in'},{label:'Equipment',value:'Live tooling, sub-spindle, magazine bar feed'}]}
]
useSeoMeta({title:'Mazak SQT-250MS Specifications by Year | UMS Spec Library',description:'Historical Mazak SQT-250MS specifications organized by year, control and configuration from UMS machinery records.'});useHead({link:[{rel:'canonical',href:'https://usedmachinerysource.com/spec-library/mazak/sqt-250ms'}]})
</script>
<style scoped>.model-page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1120px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:48px 0}.back{color:#c8d9eb;text-decoration:none}.kicker{color:#9fc4e7;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:18px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3.2rem);margin:0 0 12px}.hero p{max-width:820px;line-height:1.7}.section{padding-top:44px}.warning{background:#fff7ea;border-left:5px solid #f47b20;padding:16px 18px;border-radius:6px;margin-bottom:34px}.section h2{color:#0b2545;margin:34px 0 12px}@media(max-width:760px){.wrap{padding:0 18px}}</style>