<template><main class="page"><section class="hero"><div class="wrap"><NuxtLink to="/spec-library/machine-types" class="back">← Machine Types</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>{{typeName}}</h1><p>Historical {{typeName}} specifications organized by manufacturer and model.</p></div></section><section class="wrap section"><div v-for="m in manufacturers" :key="m.name" class="manufacturer"><h2>{{m.name}}</h2><div class="models"><NuxtLink v-for="model in m.models" :key="model" :to="modelRoute(m.name,model)" class="model">{{model}}</NuxtLink></div></div></section></main></template><script setup>
import historicalMachines from '~/assets/data/historical-machines.json'
const clean=s=>String(s||'').trim()
const slug=s=>clean(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const rows=historicalMachines.filter(m=>clean(m.Manufacturer)&&clean(m.Model)&&clean(m.WebDesc||m.Web_Desc))
const route=useRoute()
const typeName=[...new Set(rows.map(m=>clean(m.WebDesc||m.Web_Desc)))].find(t=>slug(t)===String(route.params.type||''))
if(!typeName)throw createError({statusCode:404,statusMessage:'Machine type not found'})
const typeRows=rows.filter(m=>clean(m.WebDesc||m.Web_Desc)===typeName)
const manufacturers=[...new Set(typeRows.map(m=>clean(m.Manufacturer)))].sort((a,b)=>a.localeCompare(b)).map(name=>({name,models:[...new Set(typeRows.filter(m=>clean(m.Manufacturer)===name).map(m=>clean(m.Model)))].sort((a,b)=>a.localeCompare(b))}))
const modelRoute=(m,model)=>{const ms=slug(m),mo=slug(model),t=typeName.toLowerCase();if(t.startsWith('cnc lathes'))return '/spec-library/'+ms+'/'+mo;if(t.startsWith('cnc machining centers, vertical'))return '/spec-library/'+ms+'/vmcs/'+mo;if(t.startsWith('cnc machining centers, horizontal'))return '/spec-library/'+ms+'/hmcs/'+mo;return '/spec-library/manufacturers/'+ms+'?model='+encodeURIComponent(model)}
useSeoMeta({title:typeName+' Specifications | UMS Spec Library',description:'Historical '+typeName+' specifications organized by manufacturer and model.'})
</script><style scoped>.page{color:#17273a;padding-bottom:60px}.wrap{max-width:1200px;margin:auto;padding:0 28px}.hero{background:#0b2545;color:#fff;padding:46px 0;border-bottom:4px solid #f47b20}.back{color:#c8d9eb}.kicker{color:#f47b20;font-size:.78rem;font-weight:900;letter-spacing:.12em;margin:16px 0 8px}.hero h1{font-size:clamp(2rem,4vw,3rem);margin:0}.section{padding-top:34px}.manufacturer{margin-bottom:30px}.manufacturer h2{color:#0b2545;border-bottom:1px solid #d7e0e8;padding-bottom:7px}.models{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.model{padding:11px;border:1px solid #d7e0e8;border-radius:6px;text-decoration:none;color:#1c4587;font-weight:700}@media(max-width:800px){.models{grid-template-columns:repeat(2,1fr)}.wrap{padding:0 18px}}</style>