<template>
  <main class="page">
    <section class="hero"><div class="wrap"><NuxtLink to="/spec-library/vmcs" class="back">← VMC Spec Library</NuxtLink><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>Fadal Vertical Machining Centers</h1><p>{{ records.length }} historical Fadal VMC records · {{ models.length }} model{{ models.length===1?'':'s' }}</p></div></section>
    <section class="wrap section"><h2>Fadal VMC Model Pages</h2><p class="intro">Fadal model pages are drawn directly from the historical UMS machinery records. Historical JSON presence is the inclusion rule; sold, off-market, and advertising status fields do not remove a machine from the specification library. Exact model designations remain separate where the historical database shows variants such as HT, A and other configurations.</p><input v-model="q" class="search" type="search" placeholder="Search Fadal VMC model"><div class="grid"><NuxtLink v-for="m in filtered" :key="m.slug" :to="`/spec-library/fadal/vmcs/${m.slug}`" class="card"><strong>{{m.model}}</strong><span>{{m.count}} historical record{{m.count===1?'':'s'}} · {{yearLabel(m)}}</span></NuxtLink></div><HistoricalLibraryFooter manufacturer="Fadal" machine-type="CNC Machining Centers, Vertical" /></section>
  </main>
</template>
<script setup>
import historicalMachines from '~/assets/data/historical-machines.json'
const q=ref(''),clean=s=>String(s||'').trim(),slugify=s=>clean(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),machineType=m=>clean(m.WebDesc||m.Web_Desc)
const records=historicalMachines.filter(m=>clean(m.Manufacturer).toLowerCase()==='fadal' && machineType(m)==='CNC Machining Centers, Vertical')
const models=[...new Set(records.map(m=>clean(m.Model)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map(model=>{const rows=records.filter(m=>clean(m.Model)===model),years=rows.map(m=>clean(m.Year)).filter(Boolean).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));return{model,slug:slugify(model),count:rows.length,firstYear:years[0]||'',lastYear:years.at(-1)||''}})
const filtered=computed(()=>{const x=q.value.trim().toLowerCase();return x?models.filter(m=>m.model.toLowerCase().includes(x)):models}),yearLabel=m=>!m.firstYear?'year varies/not recorded':m.firstYear===m.lastYear?m.firstYear:`${m.firstYear}–${m.lastYear}`
useSeoMeta({title:'Fadal VMC Specifications | 3016 4020 6030 | UMS Spec Library',description:'Research historical Fadal vertical machining center specifications including VMC-3016, VMC-4020, VMC-6030 and related models.'})
useHead({link:[{rel:'canonical',href:'https://www.usedmachinerysource.com/spec-library/fadal/vmcs'}]})
</script>
<style scoped>
.page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1200px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:50px 0;border-bottom:4px solid #f47b20}.back{color:#c8d9eb;text-decoration:none}.kicker{font-size:.78rem;font-weight:900;letter-spacing:.12em;color:#f47b20;margin:18px 0 8px}.hero h1{font-size:clamp(2.2rem,4vw,3.3rem);margin:0 0 14px}.hero p,.intro{max-width:940px;line-height:1.7}.section{padding-top:46px}.section h2{color:#0b2545;margin:0 0 12px}.search{width:100%;max-width:620px;padding:13px 15px;border:1px solid #aeb8c4;border-radius:6px;font-size:17px;margin:10px 0 22px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.card{display:flex;flex-direction:column;gap:5px;border:1px solid #d7e0e8;border-radius:8px;padding:14px;text-decoration:none;color:#17273a}.card:hover{border-color:#f47b20;background:#fff9f4}.card strong{color:#0b2545}.card span{font-size:.85rem;color:#6a7888}@media(max-width:850px){.grid{grid-template-columns:1fr}.wrap{padding:0 18px}}
</style>