<template><main class="page"><section class="hero"><div class="wrap"><div class="kicker">UMS MACHINERY SPECIFICATION LIBRARY</div><h1>EDM Specifications</h1><p>Historical UMS EDM records organized directly from the historical machine and specification JSON files.</p></div></section><section class="wrap section"><div class="label">MACHINE TYPES IN THIS GROUP</div><h2>EDM WebDesc Types</h2><p class="intro">These machine types come directly from the Web_Desc field on historical records whose Groups field is EDM.</p><div class="types"><span v-for="type in webDescs" :key="type">{{type}}</span></div></section><section class="wrap section"><div class="label">BROWSE BY MANUFACTURER</div><h2>EDM Manufacturers</h2><input v-model="q" class="search" type="search" placeholder="Search EDM manufacturer"><div class="grid"><NuxtLink v-for="m in filtered" :key="m.slug" :to="`/spec-library/edm/${m.slug}`" class="card"><strong>{{m.name}}</strong><span>Browse historical models and specifications</span></NuxtLink></div></section></main></template>
<script setup>
import historicalMachines from '~/assets/data/historical-machines.json'
const q=ref(''),clean=s=>String(s||'').trim(),slugify=s=>clean(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const groupMachines=historicalMachines.filter(m=>clean(m.Groups)==='EDM')
const webDescs=[...new Set(groupMachines.map(m=>clean(m.WebDesc||m.Web_Desc)).filter(Boolean))].sort((a,b)=>a.localeCompare(b))
const library=[...new Set(groupMachines.map(m=>clean(m.Manufacturer)).filter(Boolean))].sort((a,b)=>a.localeCompare(b)).map(name=>({name,slug:slugify(name)}))
const filtered=computed(()=>{const x=q.value.trim().toLowerCase();return x?library.filter(m=>m.name.toLowerCase().includes(x)):library})
useSeoMeta({title:'EDM Specifications | UMS Spec Library',description:'Research historical EDM specifications by WebDesc, manufacturer, model and year from Used Machinery Source records.'})
useHead({link:[{rel:'canonical',href:'https://www.usedmachinerysource.com/spec-library/edm'}]})
</script>
<style scoped>.page{color:#17273a;background:#fff;padding-bottom:60px}.wrap{max-width:1200px;margin:0 auto;padding:0 28px}.hero{background:linear-gradient(105deg,#071b33,#0d2c52);color:#fff;padding:52px 0;border-bottom:4px solid #f47b20}.kicker,.label{font-size:.78rem;font-weight:900;letter-spacing:.12em;color:#f47b20;margin-bottom:9px}.hero h1{font-size:clamp(2.3rem,4vw,3.5rem);margin:0 0 12px}.hero p,.intro{max-width:920px;line-height:1.7}.section{padding-top:46px}.section h2{color:#0b2545;margin:0 0 12px}.types{display:flex;flex-wrap:wrap;gap:9px;margin-top:18px}.types span{background:#f5f7fa;border:1px solid #d8e0e8;border-radius:6px;padding:9px 12px;font-weight:700;color:#0b2545}.search{width:100%;max-width:620px;padding:13px 15px;border:1px solid #aeb8c4;border-radius:6px;font-size:17px;margin:10px 0 22px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.card{display:flex;flex-direction:column;gap:5px;border:1px solid #d7e0e8;border-radius:8px;padding:14px;text-decoration:none;color:#17273a}.card:hover{border-color:#f47b20;background:#fff9f4}.card strong{color:#0b2545}.card span{font-size:.85rem;color:#6a7888}@media(max-width:850px){.grid{grid-template-columns:1fr}.wrap{padding:0 18px}}</style>